### ISSUE TITLE
BUG: Palm Rejection on Windows not Working with surface pen

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#1065]
**Your environment**
Microsoft Surface Pen, Obsidian v1.1.16, Windows 11

**Describe the bug**
When I place my palm on the screen together with the pen, sometimes my palm makes a line dashing to the left.
It happens in between writing and using palm, so I may accidentally put my palm on and off the screen, in which it takes my palm as pen input.

**To Reproduce**
1. Open an excalidraw file in a new window
2. Write with palm, and notice that there is a dash to the right. It usually happens when I am writing on the right half of the screen.

**Additional context**
Has been happening for many excalidraw versions (not just the latest).

**Comment by zsviczian** [comment]
Does turning off pinch zoom in pen mode help?
![image](https://user-images.githubusercontent.com/14358394/229280550-c7ebd72f-3fbd-4684-a96d-bbd4caf84127.png)

**Comment by devinat1** [comment]
Pinch zoom in pen mode is already disabled.

**Comment by zsviczian** [comment]
and what happens if you enable it... maybe this option is broken. I will also do some testing...

**Comment by devinat1** [comment]
Haven't encountered issues yet when it is enabled, but it could just be that I haven't encountered the issue yet.

**Comment by zsviczian** [comment]
and it also could be that the logic for the buttons is inverted. I think I heard this comment from someone else as well.

**Comment by devinat1** [comment]
I can't zoom in when the option is disabled, but I do get the bug of my palm being treated as a pen sometimes when the option is disabled.

**Comment by devinat1** [comment]
This is what it looks like when my palm gets thought of as pen input:
![image](https://user-images.githubusercontent.com/15788108/229863842-ac65c9c6-2686-430d-b000-3f2fb41a40ab.png)

**Comment by zsviczian** [comment]
I was able to reproduce the issue.
The issue is not that the setting works in reverse. The setting works ok. I hope to release a fix in the next few days...

**Comment by zsviczian** [comment]
I think this happens when pen mode is not active and you touch the screen with your palm while the freedraw tool is active. Pen mode is activated "onpointerdown" when the pointertype is "pen". Starting a line or arrow with two fingers makes sense since this is the way to draw multipoint lines on a touchscreen. The same does not make sense for the freedraw tool. Additionally, even for the line and arrow tools this feature only works properly if the first touch point is left of the second.

I will raise a PR with the excalidraw package to solve this issue.
