### ISSUE TITLE
BUG: Colors are completely broken

### ISSUE THREAD

**Issue by juh9870** [zsviczian/obsidian-excalidraw-plugin#1214]
**Your environment**

```
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.2.8
	Operating system: #1-NixOS SMP PREEMPT_DYNAMIC Wed Jul  5 17:27:38 UTC 2023 6.1.38
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Recent Files v1.3.6
		2: Advanced Tables v0.18.1
		3: Kanban v1.5.3
		4: Obsidian Charts v3.7.1
		5: Templater v1.16.0
		6: Arknights TC parser v1.0.0
		7: Hot Reload v0.1.10
		8: Excalidraw v1.9.8

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**
In the excalidraw files, all the colors are wrong.
Take this for example, I'd expect the background color to be actually red, instead of this weird light pink
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/15922601/252f4193-157b-44d7-b1f0-3eb4e367edc1)
And here white color is black for some reason
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/15922601/1805957d-ca1c-4d8d-a0d7-860464fb9d48)

**To Reproduce**
1. Open a document in web version of excalidraw website: https://excalidraw.com/#json=HW5JAemorJ_mv-DkAp2IO,v6drmarreQbmA9qfxnwYZQ
2. Export it and load it inside Obsidian
3. Notice broken colors

**Expected behavior**
Colors should match the official app and color preview

**Comment by anatoliibakhtin** [comment]
if you switch the theme from light to dark on the site the result will be the same - the problems are on the excalidraw side and it is discussed, but they have a lot of problems, so everything is done a little bit (slowly) https://github.com/excalidraw/excalidraw/issues/5312

**Comment by zsviczian** [comment]
I don't see the difference between Obsidian and excalidraw.com. See below.

As for the dark mode color change - Excalidraw.com's approach is to invert colors, which is practical for a collaborative whiteboard solution assuming multiple users, but not ideal for more artistic work. Also because Apple Safari does not support some of the SVG color transformation features, the native excalidraw.com approach results in inverted colors for embedded PNG images, which looks awful (this issue also impacts Obsidian on iPad since there Obsidian runs in a Safari window). For these reasons I personally never use the dark mode, instead, if I want a dark background I set the background color to a dark color and use a different color palette, plus I use the Excalidraw Plugin Settings/display/dynamic style set to match toolbar color to drawing background. That works well for me.

I have this video about the alternative dark mode: https://youtu.be/fypDth_-8q0 I hope this helps

Excalidraw.com - light mode:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/42faa227-74a1-47e5-b119-4c362e15753a)

Excalidraw.com - dark mode:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/e4271eac-ef80-4a26-9b69-2fceddfbcc74)

Obsidian light mode:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/cf7db68e-fd8f-446a-95ca-395d4abc5f28)

Obsidian dark mode:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/27f86054-4eb6-45f3-ae80-71d7bba7714b)

**Comment by j-r-e-i-d** [comment]
Not sure if this is related or not but the colour picker is pretty broken for me
<img width="485" alt="Screenshot 2023 07 25_12 15 46" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/96575315/6653da92-eca4-402f-903d-f489704245f7">

**Comment by juh9870** [comment]
Sorry for no response, yeah, light mode works

**Comment by j-r-e-i-d** [comment]
Hi Zsolt,
Yeah, should've checked first but you are right. it is the theme that is breaking it.

**Comment by IstyManame** [comment]
So is it getting fixed or what? Been two years the bug is still there using dark theme causes washed out colors
