### ISSUE TITLE
FR: Sync with Obsidian Wikilinks/Markdown links option

### ISSUE THREAD

**Issue by n-elia** [zsviczian/obsidian-excalidraw-plugin#1225]
**Is your feature request related to a problem? Please describe.**
Obsidian features an option, located under _Settings - Files & Links - Use [[Wikilinks]]_.
This option allows to decide whether the links generated within Obsidian environment should be in the Wikilink format (i.e. `[[link]]`) or in the standard Markdown format (i.e. `[ ](link)`).

When creating a drawing to be embedded into the current document, Excalidraw plugin ignores said setting, always producing Wikilinks.
This leads to inconsistency between link formats when using the standard Markdown format.

**Describe the solution you'd like**
It would be coherent to have the Excalidraw plugin generate the links in the same format of Obsidian.

**Additional context**
- This is the Excalidraw command to trigger for reproducing the issue:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/62206011/40ab2bff-4645-43c7-9e12-5b6d617c0721)

- This is the Obsidian setting that sets the links format:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/62206011/e76b9801-226c-41e9-80f8-16e34721634e)

- Manually changing the link format of an embedded drawing from Wikilink to Markdown leads to the same result. I would say that standard Markdown links work well with Excalidraw and should be supported.

**Comment by zsviczian** [comment]
Turns out this is already supported, though not the best solution, and the title in Plugin Settings was misleading. It's not the best because there is a separate setting in the plugin settings for the same. Anyhow I will leave it for the time being. The new setting name will appear in 1.9.9 (but the old does exactly the same)

I made one fix, however, for some reason filenames started with a space that kills markdown links. This is fixed in 1.9.9.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/a92f6ef2-44c9-4c48-98bc-1071b3a52661)
