### ISSUE TITLE
Service Not Rendering on Mac

### ISSUE THREAD

**Issue by masorick** [zsviczian/obsidian-excalidraw-plugin#123]
**Describe the bug**
Drawings do not render the canvass.

I have installed the plug in.  Using Obsidian Sync.  Canvass loads as expected on mobile, but not on my Mac.  I can make a drawing on mobile.  I see the file on my Mac, but when I open there's a blank screen.  When switching to Markdown and going into edit mode I can see the front matter and markdown generated when I made the drawing on mobile.  However the file appears to be blank when returning to drawing mode.

**To Reproduce**
1. Create new drawing

**Expected behavior**
Present canvas with tools for drawing

**Screenshots**
![Bank Canvass](https://user-images.githubusercontent.com/88851061/129244844-39f48572-17a4-4b29-b449-e4f301f26ef5.jpg)
<img width="1628" alt="Markdown View Edit Mode" src="https://user-images.githubusercontent.com/88851061/129244860-7fac853f-d7b5-4521-b6bd-f9938e31778b.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 14.1.2

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15 Public Beta
 - Browser: Safari
 - Version: Not sure

**Comment by masorick** [comment]
I deleted the Obsidian App from my Mac and then re-installed.  After doing this the plugin started to work as expected.  Sorry to bother you!  I appreciate the plug-in and will buy you a few coffees!

**Comment by TSSlade** [comment]
I had this same problem - only happened to resolve it because of the little notification pop-up in the corner of my screen said something about the old Electron version and then I hit upon some search terms that brought me here. Would it make sense to flag somewhere in the README that there's this lingering compatibility issue that people should be aware of?

I am really excited by this plugin, and would hate for people to have the same experience -- of _nothing_ happening at all -- and give up on it, when the issue is wholly external to the plugin. Just a minor comment in the installation section of the documentation indicating that (a) you may see nothing if you're running the version of Obsidian that was built on an earlier version of Electron, and (b) that running Obsidian that is fully current via in-app updates doesn't actually circumvent the problem, and you do legitimately need to delete/reinstall the app.
