### ISSUE TITLE
FR: Enable changing the "Font family" of a note embedded as "Image"

### ISSUE THREAD

**Issue by joelscampos** [zsviczian/obsidian-excalidraw-plugin#1251]
**Is your feature request related to a problem? Please describe.**
When I embed a note as "Image", the image of that note is always depicted with ("Font family" = "Hand-drawn").

**Describe the solution you'd like**
It would be awesome if we could change the image font family to "Normal".

**Describe alternatives you've considered**
I wrote some text into the current drawing, and set the "font family" to "Normal", therefore now "Normal" is the default.
Then, I inserted a note as "Image", expecting that maybe the image would be drawn using the current default "family font", but it didn't; the image was created with the "family font" "Hand drawn".

**Additional context**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2295468/c3ad5491-f717-4ed2-af36-6d4e462b2a77)

**Comment by zsviczian** [comment]
It is possible to change the font but in a different way. The UX is not great, I won't go into the reasons why I implemented it like this... the key reason is this does not effect the core Excalidraw package the plugin uses, and thus allows Obsidian to benefit from the on-going development of the Excalidraw package. You could say page embedding as image is sort of a bolt-on to Excalidraw.

This two-minute section of the video will explain how it works: https://youtu.be/tsecSfnTMow?t=52

If you are interested in more advanced feature for styling image embeds watch this video as well: https://youtu.be/K6qZkTz8GHs

Note that some of the shortcuts mentioned in the video have since changed. The latest modifier-key map is in the plugin readme: https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/images/excalidraw-modifiers.png

**Comment by joelscampos** [comment]
Thank you, Zsolt.
Placing the "excalidraw-font: Arial" property in the embedded note did the trick.
