### ISSUE TITLE
BUG: Obsidian crashes after copying image from excalidraw into obsidian .md-note

### ISSUE THREAD

**Issue by SiliasGH** [zsviczian/obsidian-excalidraw-plugin#1285]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.3
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.1.1
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 61
	Plugins enabled: 37
		1: Hider v1.3.1
		2: Advanced Tables v0.19.1
		3: Vantage - Advanced search builder v1.4.2
		4: Natural Language Dates v0.6.1
		5: Calendar v1.5.10
		6: Excalidraw v1.9.16
		7: Underline v1.2.1
		8: Outliner v4.8.0
		9: Image Toolkit v1.3.1
		10: Tasks v4.6.0
		11: Omnisearch v1.15.2
		12: Keyboard Analyzer v0.1.3
		13: Copy as HTML v1.1.3
		14: Templater v1.16.0
		15: Kanban v1.5.3
		16: Better Word Count v0.10.0
		17: Emoji Toolbar v0.4.1
		18: Hotkeys++ v0.2.7
		19: Hotkeys for templates v1.4.3
		20: Periodic Notes v0.0.17
		21: MetaEdit v1.8.2
		22: Recent Files v1.3.7
		23: Dataview v0.5.56
		24: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		25: Minimal Theme Settings v6.3.2
		26: Map View v4.0.0
		27: Style Settings v1.0.6
		28: Regex Find/Replace v1.2.0
		29: File Tree Alternative Plugin v2.3.5
		30: Commander v0.5.0
		31: Metadata Menu v0.5.1
		32: PDF Highlights v0.0.4
		33: Numerals v1.2.0
		34: Quick Latex for Obsidian v2.6.2
		35: Extended MathJax v0.4.1
		36: Tag Wrangler v0.5.11
		37: Spaced Repetition v1.10.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Copying an image out of excalidraw into a normal note, obsidian crashes

**To Reproduce**
1. Go to excalidraw, where you already have an inserted image
2. Ctrl + C the image in excalidraw
3. Ctrl + V into a normal note
4. obsidian crashes

**Comment by zsviczian** [comment]
I am able to reproduce this but don't know what to do with it, as it works as designed. You could argue the issue is on the Obsidian side, but that would also not be a fair statement. I will consult Obsidian devs on what to do with this.

All the images that you embed into Excalidraw are separate files in your Vault. You should reference those same image files in your Obsidian notes and not copy the image element. When you copy the element it places a large text on the clipboard that is the encoded image in an excalidraw.json format. This is what allows excalidraw.com to receive the image should you paste your image there. If you want to find out the link to the image in your drawing the current process is a bit cumbersome: you need to CTRL+click on the image in excalidraw, this will open the image in a new tab. You can then copy the name of the tab (click rename file) and use that in your wiki link in the Obsidian note. There are other approaches as well, opening your drawing in markdown view mode and copying the link from there, or opening the image in a new window, then using the recent files plugin and dropping the file to your markdown note, etc...

[This is a sample of the data](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/12446538/clipboard.data.txt) that obsidian tries to paste and stalls. It does not really crash just takes a very long time to process

**Comment by zsviczian** [comment]
Thanks for raising this. I fixed this in 1.9.18. Will release later today.
