### ISSUE TITLE
BUG: Left over code. Markdown file is not very clean

### ISSUE THREAD

**Issue by Serinki** [zsviczian/obsidian-excalidraw-plugin#1288]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.5
	Operating system: Windows 10 Education 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.1.2
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 41
	

**Describe the bug**
Afer inserting and deleting some elements, the markdown file of the drawing is not very clean

**To Reproduce**
1. Click button: Insert any file from your vault
3. Delete the inserted image/ iframe
4. There are still left-over code in the markdown file  even though the canvas is blank

**Expected behavior**
I expected the markdown file would be reset to default state

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/105690155/fcb45e2e-22d9-4736-b0d8-c6823425f124)

**Comment by zsviczian** [comment]
This is as designed. Notice, that the elements have `"isDeleted": true`.  This is required because if you delete elements on one device, then sync your drawing to another with e.g. with Obsidian sync, I need to know what was deleted on device A to successfully combine with potential changes on device B. If you need a clean drawing you need to create a new drawing or switch to markdown view, then switch back to Excalidraw view and switch to markdown view again as this process will purge the residue isDeleted: true items.
