### ISSUE TITLE
FR: Adjusting sub-grid size

### ISSUE THREAD

**Issue by HafiTheCat** [zsviczian/obsidian-excalidraw-plugin#1305]
**Is your feature request related to a problem? Please describe.**
Since the better grid system got introduced, there is now a sub-grid within the actual grid.
I personally like to work with the grid enabled at all times. However, since the sub-grid consists of an odd number of cells (currently 5), it makes diagram-like connections not aligned to an element anymore (when snapping).

**Describe the solution you'd like**
Either, set the sub-grid cells to an even number like 4, 6, 8 or update the *Set Grid* script to make it possible to change the sub-grid as well.

A better solution might be to have the settings for the grid and sub-grid size in excalidraw itself.

**Describe alternatives you've considered**
I have tried changing the grid size with the *Set Grid* script, however this changed only the outer grid and not the sub-grid, since it is not updated to the new grid system.

**Additional context**
At the top, the link between the elements snaps to the grid lines. It is not centered because the amount of cells within the outer grid cell is an odd number.
At the bottom, the link should snap in the middle of the element (since the grid in the bottom reference is still 5 sub-grid cells the sub-grid does not align of course)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/58081895/be64e3cb-6c3b-484d-837a-cb86c5a0ec47)

**Comment by zsviczian** [comment]
Set Grid does work with the new grid system. What you should keep in mind is that major grids are always relative to the grid size.

So with the default grid of 20, you will get an object of 100x100 if you follow the major grid and an object of 20x20 if you follow the minor grid:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/ddea8916-fdf3-46eb-9b63-565c3b703c5f)

With a grid size of 10 you get an object of 50x50
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/8db1b919-cdd5-4cf0-abdf-e529dbedaa69)

With 1.9.19 I will release an updated setGrid script that will allow you to set a custom number of minor grids between major grids. i.e. instead of the current pattern of every fifth line being stronger, you could set it to be every sixth, or whatever.
