### ISSUE TITLE
BUG:hotkeys doesn't work with different keyboard layout - not english

### ISSUE THREAD

**Issue by ae0nf1ux** [zsviczian/obsidian-excalidraw-plugin#1359]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Windows 10 Home Single Language 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v1.9.23

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
hotkeys do not work with a different layout  - not english

**To Reproduce**
example, I want to change from selection to hand tool by pressing H with different layout but that doesn't work

**Expected behavior**
I expected that I'll change from selection to hand tool

**Comment by zsviczian** [comment]
Yes, this is a known issue, but not Obsidian specific. In addition, in Obsidian a number of hotkeys don't work because Obsidian overrides them.

What works (I also use a non-English layout) is pressing the button that matches the English layout. Check the shortcut, then look at a picture of a keyboard with the English layout and press the corresponding button on your own keyboard. In most cases (when Obsidian is not overriding shortcuts) this approach works for me.
