### ISSUE TITLE
BUG: 框选后引用区域，非常卡顿，引用的内容图片出不来

### ISSUE THREAD

**Issue by violentrant** [zsviczian/obsidian-excalidraw-plugin#1393]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

全平台

**Describe the bug**

BUG: 框选后引用区域，非常卡顿，引用的内容图片出不来

**To Reproduce**
复制链接
**Expected behavior**

**Screenshots**

**Additional context**

希望可以多选选区，多项同时复制链接，复制到新的md文档中。
目前引用图片刷不出来。

**Comment by zsviczian** [comment]
I don't understand what type of frames you are talking about. Embedded markdowns in interactive frames?
How many do you have in your drawing?
A screenshot and a step-by-step description will help me understand the issue you are facing.

Please include the debug info. It helps me understand not only the platform you are using but what other plugins you have installed because often issues are caused by plugins not working well together.

**Comment by violentrant** [comment]
![IMG_20231023_131021](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/37677673/38dc6b7e-0926-49ce-b34e-0bbbaec39588)
![IMG_20231023_131152](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/37677673/2af9169c-d282-4c7f-be24-375744bbd829)

![IMG_20231023_131340](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/37677673/79ba969f-235a-40b5-b3bf-dbcad5140508)

u can see the word in pic

**Comment by violentrant** [comment]
if i can choose all the frame aera  and can copy the aera to the new md file to study more deep will be best

**Comment by violentrant** [comment]
hi the issue is that ，hope you can solve it



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月23日(周一) 中午12:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zsviczian/obsidian-excalidraw-plugin] BUG: 框选后引用区域，非常卡顿，引用的内容图片出不来 (Issue #1393)




 
I don't understand what type of frames you are talking about. Embedded markdowns in interactive frames?
 How many do you have in your drawing?
 A screenshot and a step-by-step description will help me understand the issue you are facing.
 
Please include the debug info. It helps me understand not only the platform you are using but what other plugins you have installed because often issues are caused by plugins not working well together.

**Comment by zsviczian** [comment]
I am adding a feature to 1.9.27 to change the PDF scale (resolution) - which should speed up the PDF import.
An area link on a PDF page will be slow because the entire page needs to be loaded with all the PDF pages, and then the area will be cut. For this usecase I do not advise the area link.

Once 1.9.27 is released you can try setting the PDF Scale to a lower value to see if it speeds up the process for you sufficiently.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/41ac45d3-1bae-4e1c-aa10-33fcc4eff3c5)

**Comment by violentrant** [comment]
> I am adding a feature to 1.9.27 to change the PDF scale (resolution) - which should speed up the PDF import. An area link on a PDF page will be slow because the entire page needs to be loaded with all the PDF pages, and then the area will be cut. For this usecase I do not advise the area link.
> 
> Once 1.9.27 is released you can try setting the PDF Scale to a lower value to see if it speeds up the process for you sufficiently. ![image](https://user-images.githubusercontent.com/14358394/278830475-41ac45d3-1bae-4e1c-aa10-33fcc4eff3c5.png)

thank u very much，you code is best for us🌝🌝。hope u code will belp more and more person using
