### ISSUE TITLE
BUG: Embedded note in drawing issue when PNG export

### ISSUE THREAD

**Issue by Atiroocky** [zsviczian/obsidian-excalidraw-plugin#1449]
**Your environment**

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Pro for Workstations 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things v2.1.13
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 17
		1: Quick Latex for Obsidian v2.6.3
		2: Mind Map v1.1.0
		3: Excalidraw v2.0.1
		4: Dataview v0.5.64
		5: Excel to Markdown Table v0.4.0
		6: Style Settings v1.0.7
		7: Obsidian Charts v3.8.2
		8: Note Refactor v1.8.2
		9: Obsidian Functionplot v1.2.1
		10: Admonition v10.1.1
		11: Pandoc Plugin v0.4.1
		12: Code Block Enhancer v1.0.5
		13: Numerals v1.2.0
		14: ExcaliBrain v0.2.11
		15: Linter v1.20.1
		16: Templater v1.18.0
		17: Desmos v0.6.6

**Describe the bug**
I love to used Excalidraw, but I have an issue that I can’t figure out.
Here is an example : on my Excalidraw drawing, I import the same note from my vault, as embedded (left) or image (right),

When I export this drawing as PNG, the embedded note is not showing, only the link appears.
Whereas the note imported as PNG, is correctly shown.

Il looks the same result when I embed this drawing to a another note.

**Expected behavior**
I want the export PNG image to show the embedded note correctly.
Is there an option to tick or untick ?

**Screenshots**
Original drawing :
![Excalidraw](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/143591751/8ce8fd87-4715-4eb2-a129-e5d2fc321cbd)

Export as PNG :

![Export copy to clipboard](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/143591751/aa8aba4f-f15e-4fe2-b37e-452cfd5bf796)

Embedded drawing in note :

![Note](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/143591751/1aac081d-8620-4f23-a35a-fca4c2bd4166)

**Comment by zsviczian** [comment]
you can embed a markdown note as an image or an embeddable. Use the add any function, or the right modifier key. See readme for the modifier keys.
Embeddables are not included in the image export - that is as per design.

**Comment by DelmarHuang** [comment]
May I wonder why it is designed that embeddables are not included in the image export? Now I have to take screenshots, which is very annoying.

**Comment by zsviczian** [comment]
primarily for performance reasons, there is also a webview security consideration, just because you can see it on screen, I cannot see it from code. So if you embed a webpage for instance, from code I cannot take a screenshot of the webpage you are looking at. This is a basic web-browser security which is super useful for many reasons, but because Obsidian technically runs in a web browser (Electron browsers on desktops and different webview components on iOS and Android) the same web limitations apply. This means that for webpages it is to the best of my knowledge impossible to create a screenshot where embeddable in iframes or webview components are included in the image, for markdown notes I do plan to make use of the markdown to image feature which you can already use if you chose to embed a markdown document as an image not as an interactive frame, but that will look different and I know that will be the next question... so I did not start off on this path.

When I need a picture of a board with embeds I simply take a screenshot. It is not elegant, but it works, and I don't have a better solution.

There are a number of additional reasons as well, but these two are the main ones.

**Comment by DelmarHuang** [comment]
I see now. Thank you very much for this detailed explanation. Good night!
