### ISSUE TITLE
[FR] Embed directly SVG/PNG file

### ISSUE THREAD

**Issue by Mara-Li** [zsviczian/obsidian-excalidraw-plugin#149]
**Is your feature request related to a problem? Please describe.**
When I want to share my file, or just check it, I have some problem between the .embed.md and I need to rename it with SVG/PNG.

**Describe the solution you'd like**
Add an option in settings to change the format of the embeding feature (the `create new drawing and embed it in the current document`) between *.excalidraw.md to *.svg or *.png

**Describe alternatives you've considered**
For the moment, I rename it manually. I also could create a little templater script, but I will really prefer to have the option in excalidraw. 

**Additional context**
/

**Comment by zsviczian** [comment]
Hi Mara-Li, just to make sure I fully understand your request. You have the export settings turned on:
![image](https://user-images.githubusercontent.com/14358394/134289529-b379facb-459d-4793-9244-df541e94f254.png)
And you would like to insert the to-be created .png or .svg into your document instead of the .excalidraw.

I can do this. I am thinking that this command palette option would only show if you have the matching auto-export feature turned on in settings.

Did I get it right?

**Comment by zsviczian** [comment]
See [v1.3.12](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.12)

**Comment by Mara-Li** [comment]
Perfect ! Thank you a lot :D
