### ISSUE TITLE
Black or red fonts appear grey in the notes when using the Blue Topaz theme

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#15]
![image](https://user-images.githubusercontent.com/29135984/115994007-ddbc0200-a607-11eb-9d28-d9ad21412986.png)

![image](https://user-images.githubusercontent.com/29135984/115994020-ef050e80-a607-11eb-9ba1-953b3bcac579.png)

**Comment by zsviczian** [comment]
So this is a CSS issue. I can't reproduce it at the moment but have seen the same issue with some users in Roam. What Obsidian theme are you using? Do you have any additional custom CSS?

Is the drawing set to transparent? can you share the .excalidraw file so I can try to reproduce the error on my side?

**Comment by zhl111** [comment]
theme ：Blue Topaz
 custom CSS? yes,after I turn off the custom css, the github icon is still on the left side.But Zen mode is ok
sliding panes? yes

**Comment by zsviczian** [comment]
So you need to raise the issue with the Blue Topaz developer. The gray color is due to these lines in the blue topaz.css at row 4023.

```
g text{
  fill:var(--text-muted) !important;
}

#arrowhead,  #sequencenumber,  .cluster text,  .label text,  text,  text.actor {
  fill:var(--text-muted) !important;
}
```

You can also fix this for yourself by editing `.obsidian/themes/Blue Topaz.css` and changing the above to this (essentially removing the `g text` rule and removing `text` from the second rule):

```
/*
g text{
  fill:var(--text-muted) !important;
}
*/

#arrowhead,  #sequencenumber,  .cluster text,  .label text,  text.actor {
  fill:var(--text-muted) !important;
}
```


The github icon is also due to Blue Topaz.css, but I will take care of that by hiding the icon.
