### ISSUE TITLE
BUG: In Android, the stoke width is different between line mode and draw mode (Windows version is good) 

### ISSUE THREAD

**Issue by hunklin** [zsviczian/obsidian-excalidraw-plugin#1521]
**Your environment**
Android cellphone and tablet, obsidian w/ excalidraw plugin

**Describe the bug**
When I use Android to draw an excalidraw, with the same stroke width setting, If I use an R key or L key to draw a line, it is small, but if I use the P key to draw in the drawing mode, it is big. See the picture below.
But in the Windows they are the same width. So Windows version doesn't have this issue.

**To Reproduce**
If I use an R key or L key to draw a line, it is small, but if I use the P key to draw in the drawing mode, it is big. 

**Expected behavior**
The width should be similar

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/31301796/1c4bd565-0b65-4b7f-b477-27d58cc7c2e1)

**Additional context**
source file in Android
[Drawing test.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13774484/Drawing.test.excalidraw.md)

**Comment by zsviczian** [comment]
This is a known issue and has been extensively discussed but without a solution. The key issue is backward compatibility of drawings: https://github.com/excalidraw/excalidraw/issues/3693

I will close the issue here as this needs to be solved on Excalidraw.com, not in the Obsidian plugin. Feel free to add your comment to the issue on the link above.
