### ISSUE TITLE
Resize the excalidraw pane contents, when another obsidian note is opened on the side concurrently

### ISSUE THREAD

**Issue by Fierce-Ninja** [zsviczian/obsidian-excalidraw-plugin#159]
**Describe the bug**
When I open a new note on the side while keeping the excalidraw pane open, the pane itself resizes but the contents inside are hidden as they don't resize. Please let me know if this is a bug or I am overlooking something. If not, this would be a very helpful feature to add!

**To Reproduce**
1. Open an excalidraw note. Now open another note on the side (without closing the excalidraw note).
2. The contents of the excalidraw note do not resize and part of them seem to be hidden below the open side note.

**Expected behavior**
The contents of the excalidraw window should resize.  

**Screenshots**
![image](https://user-images.githubusercontent.com/12793089/135548382-0afcbc5a-2520-4f53-b8fa-c7f8bbecd469.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Obsidian Version 0.12.15

**Comment by zsviczian** [comment]
This is by design, as I do not know the reason for resizing the window. If you are zoomed in to an area in your drawing and increase change the window size (i.e. open Obsidian full screen), it would be inconvenient if Excalidraw did a zoom-to-fit.

But I think you are right, it is probably more natural to zoom-to-fit after the window size changes. I have added a setting, by default it set to allow zoom-to-fit on resize. If someone does not like this, they can turn the feature off.

It will be available in the next update.
