### ISSUE TITLE
FR: Image Size Zoom

### ISSUE THREAD

**Issue by pablo-hp** [zsviczian/obsidian-excalidraw-plugin#1695]
Why is it that when I paste an image that is on the clipboard and zoom into the document, when I try to paste the same image again, it pastes the image from the clipboard, but with a smaller size?

It would be more correct to respect the zoom level when pasting the same image, thus maintaining the correct size and proportion of the image. I.e,
the same image, with the same size, regardless of the zoom of the document, it respects the real dimensions of the image.

I don't know if I managed to explain it correctly, but when pasting the same image from the clipboard, but with a different zoom, the image is also pasted with different sizes.
I would like it to respect the actual size of the image and not the zoom of the document.
I don't know if this is possible.

Try pasting the same image from the clipboard, with 100% zoom, 50% zoom and 150% zoom and you will see that the images are pasted with different sizes.

**Comment by zsviczian** [comment]
I think people will have very different preferences regarding this.
I can think about a CTRL+SHIFT paste option when the original aspect ratio is maintained...
decreasing the size relative to zoom level is done, as otherwise in some situations the pasted image would occupy the whole screen (and more).

You can set a hotkey for the command palette action "Set selected image element size to 100% of original". (not that currently this command palette action only works if the file was saved after inserting the image. I am fixing this in 2.1.2 (soon to be released).
