### ISSUE TITLE
BUG: Excalidraw obsidian not honouring change in image aspect ratio.

### ISSUE THREAD

**Issue by FancyBEAST** [zsviczian/obsidian-excalidraw-plugin#1698]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.11
	Operating system: Windows 10 Home Single Language 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.1.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
When saved a drawing after resizing the image if the aspect ratio of the image is changed then it reverts back to the original.

**To Reproduce**
1. Insert an Image in excalidraw
2. Resize it while holding shift key to change it's aspect ratio
3. Save the file and the image aspect ratio reverts back to original

**Expected behavior**
Excalidraw obsidian should honour the change in aspect ratio

**Screenshots**
https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/30184625/5d5acd93-57d3-4a98-9f3f-af422d22b1c4

**Comment by zsviczian** [comment]
fixed in 2.1.2.
In the future changes in aspect ration of jpg, png, bmp, SVG, etc. will be honored. Changes to aspect ratio of embedded (nested) Excalidraw drawings will still not be honored, because I don't see a way of discerning if the aspect ratio of the nested drawing has changed, or you deliberately set a different aspect ratio for the image on the canvas.
