### ISSUE TITLE
FR: Grid turned on by default on new drawings

### ISSUE THREAD

**Issue by Mug521** [zsviczian/obsidian-excalidraw-plugin#1703]
I've seen that the option to set the grid on by default is not in the Excalidraw settings, you have to set it on for each new draw. I would love to see it as an option, after testing the grid out I'm always using it now (it's amazing, way more organizated)

**Is your feature request related to a problem? Please describe.**
Each time I open a new drawing I have to manually enable the grid. I think it will be way more practical to just have to option to let it always enabled.

**Describe the solution you'd like**
The option to set the grid as default in the Excalidraw settings, to set the grid on by default in each new drawing.

**Comment by zsviczian** [comment]
Create a template file for Excalidraw and configure it in plugin settings (under Basic). Changes you make to the template file (default font, colors, line width, grid on or off, background color, etc.) will be applied to any new drawing you create. You can even have multiple templates to chose from by setting a folder for templates instead of a single file. Because some of the settings, such as turning on Grid do not by default trigger save of the drawing, once you configured your template (e.g. you turned on grid) make sure you press CTRL+S (this is CTRL on Mac as well) to force save your template.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/608e2fff-8c27-4368-a57f-a5fc3fdf0037)
