### ISSUE TITLE
When in full screen mode the command palette will not appear

### ISSUE THREAD

**Issue by GitMurf** [zsviczian/obsidian-excalidraw-plugin#176]
I am not sure if this is a bug or by design or just tricky but sometimes I want to open the command palette when I am in full screen mode in excalidraw and it throws me off that it doesn't work. It always takes me a bit to remember/realize I have to exit full screen mode and then try to re open the command palette.

**Comment by zsviczian** [comment]
That is a bummer. Issue is, I can’t get it to work. I am using element.requestFullScreen(), and it has this side effect. I tried resizing the containerElement to full screen and changing the z-order, but that had other issues, because some of the components on screen in default Obsidian have a higher z-order then popup dialogs.  for now I don’t know how to fix this. If you have a good solution, I’d love to hear that.

**Comment by zsviczian** [comment]
solved the command palette issue in 1.5.7
The solution is a MutationObserver to move the modal div under the fullscreen div

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/b6c5bfb20a684fa074df4cdd16a938d4678c39b1/src/ExcalidrawView.ts#L348-L380
