### ISSUE TITLE
FR: Crop Function in Gear Menu above PDF

### ISSUE THREAD

**Issue by Vonnegut1** [zsviczian/obsidian-excalidraw-plugin#1779]
There is a lot of friction in opening a PDF, finding the image and then having to go through the crop tool to get back what you want on the Excalidraw canvas. The crop tool is also inconsistent when you drag a PDF onto the canvas from your files. control+p can't find the tool.

Feature request: A crop icon in the gear menu triggers a crop tool around an image you want to clip on the PDF page. That creates the image on the canvas with a link back to its source,

**Comment by zsviczian** [comment]
The issue you described in Discord is likely because prior to Excalidraw 2.2.0 dragging and dropping a PDF from your OS did not import the file to Obsidian, and cropping only works on imported PDFs. In 2.2.0 when you drag and drop a PDF from the OS it will by default import the PDF to the Vault and you'll be prompted for action to import as an embeddable or as images.

**Comment by zsviczian** [comment]
solve in 2.2.0
