### ISSUE TITLE
Image Inline

### ISSUE THREAD

**Issue by pablo-hp** [zsviczian/obsidian-excalidraw-plugin#1824]
Image Inline
Embedded image

Hello.
Obsidian currently has a plugin called Image Inline.

Simply what it does is:

_"Sometimes you just don't want images saved as separate files, cluttering up your workspace. This plugin meets this need,
allowing you to convert images to base64 encoded strings and embed them directly into your notes.
I wish Excalidraw for Obsidian had this feature."_

How do I use obsidian plugins in excalidraw? 
Would it be possible to create a plugin for excalidraw that does exactly the same thing?
I would like to have my images directly in excalidraw without the need for a separate file.

**Comment by zsviczian** [comment]
I am sorry, but I do not see the value of this feature. The whole idea of Excalidraw in Obsidian is to make images linkable and reusable. Why not paste images to a dedicated directory, if you feel they clutter your folders?

**Comment by HoodyEz** [comment]
Some time ago, the function to add images as URLs was added, which saves space when adding images that are not intended to be used in other notes. However, the idea seems interesting to me. Personally, I don't usually reuse the images I add to my notes except in some cases; I mostly reference other notes and Excalidraw drawings to create links. In any case, if the problem is that you don't want to clutter your vault with images, I recommend using the 'Clear Unused Images' plugin to delete images that are not linked to anything, as well as pasting images as URLs if you have internet access all the time.

**Comment by zsviczian** [comment]
I'll think about the feature of allowing to embed images in the Excalidraw file. Technically it is not difficult. Making it intuitive in the app is. Also the larger the files, the slower Obsidian indexing will be. It is not a good idea to unnecessarily increase the size of markdown files. That is not Obsidian is designed to handle.

Regarding images with URLs. I've resisted this feature for a long time. I still don't think it is a good choice, but the plugin supports it. My thinking is, I still use notes from 25+ years ago. Images from webpages often go blank already after half a year, 2-3 years at best. I don't think it is wise to build a PKM on such an instable footing.

As for Vault size, base64 is not a very efficient format, it will add 20-30% to images size. But yes, it does remove some clutter from folders... though you could place images in a dedicated resources folder and then this becomes a non-issue.

Finally, on the topic of "clear Unused Images", I personally avoid any plugins that delete or modify files on a mass basis. You can never predict unintended collateral consequences (or plugin errors). Also I have images that are not linked to other files, but simply reside in a folder, because the folder is a form of linking in itself. I rather stick to habits to clean up anything I don't need immediately when I don't need it. Excalidraw has a command palette action `Delete selected image or Markdown file from Obsidian Vault`. I have a hotkey for this. If I know I want to discard the image, I use this instead of simply deleting the image from the drawing, because a simple delete will retain the file in the folder.

**Comment by pablo-hp** [comment]
Thanks for your answer and time.
