### ISSUE TITLE
BUG: 2.2.6 Update

### ISSUE THREAD

**Issue by zanodor** [zsviczian/obsidian-excalidraw-plugin#1826]
Zsolti, I was on Linux updating the sole plugin (Excalidraw) before turning in for the night and felt navigation in Obsidian settings sluggish. Deactivating Excalidraw made it okay again.

Something's off. Just thought I'd shoot this up.

Cheers

**Comment by zsviczian** [comment]
Please share the Obsidian Debug info with your issue, as explicitly requested in the bug form. Without that, I cannot really do anything with your feedback as it lacks necessary info. It is not by hobby I ask for this info, but to be able to help you. This way, I can't.

What you describe is often the impact of some other plugins, not Excalidraw directly. Metadata Menu is one of the frequent culprits. Some of the Obsidian themes also cause this.

Please test with the base Obsidian theme, disabling your css snippets, and disabling other plugins.  Best to restart Obsidian after you turned everything off (except for Excalidraw). Let me know if you can still experience the performance issue.

**Comment by zsviczian** [comment]
5 minutes after the plugin starts I run a cleanup of cached images. You may try to purge image cache in plugin settings and see if that has any effect.

**Comment by zsviczian** [comment]
This could then be related to loading of the plugin css. Excalidraw has a pretty extensive css stylesheet. Styling, especially when stacked on top of one another by different plugins can have a very significant performance impact.
From the plugin list I see you have many plugins that play with CSS... so that is the likely explanation.
