### ISSUE TITLE
BUG: When importing an image from my computer, how can I set the image's link format to be in Markdown type, and how can I control the image's name?

### ISSUE THREAD

**Issue by distantlullaby** [zsviczian/obsidian-excalidraw-plugin#1863]
## as i see this option doesn't work
![image](https://github.com/excalidraw/excalidraw/assets/89437037/741d4c9c-c413-4732-9547-c39d6ce42673)
![image](https://github.com/excalidraw/excalidraw/assets/89437037/65a16264-0137-4061-b602-0bac5a42544c)

## after importing an image,the original image'name has been edited,
![image](https://github.com/excalidraw/excalidraw/assets/89437037/b13180b3-8d2e-4025-9e83-04cf909f9d07)

**Comment by zsviczian** [comment]
markdown links are not supported under the Embedded Files section.
Why would you need that??

you can rename the image as any other file in Obsidian (in the Obsidian file explorer simply right click and select rename).
I also have a script "rename image" available in the Excalidraw script store. Then you can select an image and rename it in the drawing.
Finally if you drag and drop the image from your PC instead of using the add image button, then it will retain the filename from your local drive. (note, there is a bug in 2.2.8 which will result in duplicated images when you drag and drop images from the local file system. this will be fixed in 2.2.9.
