### ISSUE TITLE
BUG: EXcalidraw's embedded css is different from all other modes

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1929]
![4](https://github.com/user-attachments/assets/cd678130-782a-4896-87f5-f1e8b5c7897d)
As shown in the figure, EXcalidraw is embedded differently than any other mode
The embedding of the behavior EXcalidraw can remain the same as other patterns
This is something that has been bothering me for a long time, my various css are not working with embedded content in EXcalidraw, hopefully it will be fixed

**Comment by zsviczian** [comment]
Sorry but, I don't think this is something I can fix - and I also can't reproduce it.
Theme designers test for Canvas compatibility and not for Excalidraw. Because Excalidraw objects run under a DOM object that has the class Excalidraw, CSS that is designed with absolute DOM references instead of relative references will not work the same way for markdown embeddables in Excalidraw. 

Here are two examples I tested. The default obsidian theme and Obsidian Gruvbox (the one I use)

https://github.com/user-attachments/assets/19984cff-aa09-45a9-8d9a-5a4da2ca2e7a


https://github.com/user-attachments/assets/652d5716-d03d-4752-b991-9fab0334c997
