### ISSUE TITLE
Error loading drawing: Unexpected end of JSON input

### ISSUE THREAD

**Issue by crissxross** [zsviczian/obsidian-excalidraw-plugin#193]
**Describe the bug**
My (complex) excalidraw drawing does not render/open as an Excalidraw drawing when I click 'Open as Excalidraw Drawing' and the following error message appears:

_Error loading drawing:
Unexpected end of JSON input
Try manually fixing the file or restoring an earlier version from sync history_

This happened after I updated a number of plugins, including Excalidraw, whilst the drawing in question was open (as an Excalidraw drawing) in a pane in the background.

The drawing JSON is truncated and missing data towards the end. The beginning and end sections of the JSON are shown below:

%%
# Drawing
```json
{"type":"excalidraw","version":2,"source":"https://excalidraw.com","elements":[{"type":"text","version":56,"versionNonce":93100881,"isDeleted":false,"id":"o8QpUTbw","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":-708.4844360351562,"y":-423.25048828125,"strokeColor":"#862e9c","backgroundColor":"white","width":90,"height":25,"seed":2115032017,"groupIds":[],"strokeSharpness":"sharp","boundElementIds":[],"fontSize":20,"fontFamily":1,"text":"DAY ONE","rawText":"DAY ONE","baseline":18,"textAlign":"left","verticalAlign":"top"},
... etc. ...
{"type":"rectangle","version":46,"versionNonce":746329753,"isDeleted":false,"id":"SIdle2Jv","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","rou
```

Please note: I did not manually, accidentally delete the drawing's JSON data.

**To Reproduce**
Steps to reproduce the behavior: see above.

**Expected behavior**
It should render an excalidraw drawing as an Excalidraw drawing

**Desktop (please complete the following information):**
 - MacOS 11.5.2
 - Chrome
 - Version 94

**Additional context**
I can't restore the data of the corrupted drawing because it was a new drawing, I don't have Obsidian sync and I hadn't yet saved a copy to GitHub manually. 

I've now backed up the vault to GitHub and checked my other Excalidraw drawings which are fine. They are equally complex but none of them were open when I updated my plugins (including Excalidraw).

**Comment by superouioui** [comment]
I have the same problem on the drawings having texts

**Comment by crissxross** [comment]
It has happened again on a recreated version of the same Excalidraw complex drawing. Again this was after I updated my plugins, including Excalidraw, but this time I didn't have an Excalidraw drawing open at the time.

I'm wondering if there's a maximum size that Excalidraw can handle beyond which it starts to truncate the code?

@mure The plugins I have installed & activated:

Auto Link Title
Carry-Forward
Checklist
CodeView
Dataview
Excalidraw
Fullscreen mode plugin
Hotkey Helper
Juggl
Open vault in VSCode
Ozan's Image in Editor Plugin
Pane Relief
Reading Time
Reset Font Size
Show Whitespace
Tag Wrangler
Templater
Workspaces Plus

(Sorry for the delay, notifications were going into my junk email box)

**Comment by swehba** [comment]
I have also experienced this problem. I lost an entire, large drawing due to it. I tried creating a new drawing consisting of a single rectangle — same error. At this point, Excalidraw is completely unusable for me.

**Comment by swehba** [comment]
This is a serious bug that needs to be addressed before any new features are added. If I try to create a simple drawing consisting of one rectangle, save it, click on another note and then back on the Excalidraw diagram, I get his note instead:

https://cln.sh/WTK1t1+

And the diagram does not render. This is an absolute show-stopper bug...at least for me. I have to image others are also experiencing it.

Incidentally I don't see an "Excalidraw View" item in the menu for this page.

**Comment by zsviczian** [comment]
I've done several improvements to saving since the time of these issues. 
Personally it's been many month since I last experienced data loss such that I had to reach back to the Obsidian sync history to fix it.

In settings you can now specify autosave. I recommend setting the autosave timer to 15 seconds.

Obsidian does not wait for plugins to complete saving when you terminate the application, thus as a general practice you should not terminate Obsidian without first clicking the save button in Excalidraw. The save button will be red when there are unsaved changes. The same applies for using Excalidraw on a mobile device, you should tap save before changing apps, because your operating system might recycle the active Obsidian thread, and your drawing might not get saved. You do not need to worry about pressing save when opening and closing documents within Obsidian. As long as Obsidian is not terminated, Excalidraw will always save before closing, and before losing focus to another workpane.
