### ISSUE TITLE
BUG: The Excalidraw Writing Machine work wierd with a path including chinese characters

### ISSUE THREAD

**Issue by xllowl** [zsviczian/obsidian-excalidraw-plugin#1961]
** environment**
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.3
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 23.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Primary v2.8.0
	Snippets enabled: 31
	Restricted mode: off
	Plugins installed: 167
	Plugins enabled: 89

**Describe the bug**
The Excalidraw Writing Machine work wierd with a path including chinese characters.This will makes the image include in the final file very small.
I think the problem is the path changing does not works well.

**To Reproduce**
Having the path with chinese characters

**Solutions**
- Change the path with English
- Use the ![[wikilink]] instead of the ![]() form

**Comment by zsviczian** [comment]
According to chatGPT the encoder function I am using should support Chinses characters correctly... so I am not sure what I can do with that.
I released an update of the script, you can open the script library and install it.
After you run the script once, you can open settings and a new setting will appear to use wikilinks instead of markdown links.
