### ISSUE TITLE
BUG: The suspension window is no longer usable

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#2041]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 18
	Restricted mode: off
	Plugins installed: 84
	Plugins enabled: 2
		1: Excalidraw v2.5.0
		2: Hover Editor v0.11.20

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

![5](https://github.com/user-attachments/assets/801dcbbf-605c-421a-a049-a79ef62d78b9)
The suspension window doesn't work. It disappears when you open it
Although hover editor is not a core plugin, several bugs about it have been mentioned, but have been ignored
But hopefully this time we can handle it,
It is a must-have plugin for me and many others, and the small bugs before can only waste a little time to endure
But this time can not be used directly, it is too big a shock

**Comment by zsviczian** [comment]
I am sorry, but I am not looking into issues caused by other plugins.
However, editable previews are now available in Obsidian 1.7.3, which work as expected with Excalidraw.

**Comment by jiajiala** [comment]
Thank you for your message
Always sorry to use your plugin for free
It is a pity that my financial situation is not very good

Thank you so much for making this awesome plugin

**Comment by jiajiala** [comment]
> I am sorry, but I am not looking into issues caused by other plugins.抱歉，我不会调查其他插件引起的问题。 However, editable previews are now available in Obsidian 1.7.3, which work as expected with Excalidraw.不过，Obsidian 1.7.3 中现在提供了可编辑预览，它可以与 Excalidraw 一起按预期工作。

After updating to 1.7, excalidraw is still unable to be compatible with hover editors, because the hover editor can't be replaced for a while, so I can't update excalidraw

**Comment by zsviczian** [comment]
I am sorry to hear that, however you will need to work this issue with the developer of Hover Editor. 
Excalidraw works as expected with Obsidian editable previews. Is that not an alternative?

https://github.com/user-attachments/assets/a5f29336-7bc4-4051-a3ff-21bdc06ac945

**Comment by jiajiala** [comment]
Well, I'll try to see if the makers of the hover editor can't be compatible with excalidrawMainly, obsidian's own editorial preview is very bad to use, not to be stuck, and no crumbs can be viewed in context

**Comment by pjeby** [comment]
Excalidraw is deliberately closing the hover editor window in response to a mouseover event (among others).  It is looking for an `.embed?.edtior` property, and if one is not found, it closes any hover popover it found, instead of allowing it to close normally.

I'm not sure why this behavior is necessary, and I could perhaps change Hover Editor to fake what Excalidraw is looking for here (though that might break *other* plugins), but perhaps we can work out some better way to address this?

It looks like Excalidraw has a *lot* of custom logic for handling hover previews, and that logic is different from both Obsidian's default and Hover Editor's.  (e.g., popovers are not normally immediately closed by either Obsidian or HE).

**Comment by jiajiala** [comment]
Yes, EXcalidraw has a lot of custom hover preview logic
I can't open the same floating window twice in EXcalidraw
A suspended window of the same file can only trigger one via EXcalidraw

**Comment by pjeby** [comment]
It looks like the closing behavior was introduced in Excalidraw 2.5 to avoid closing active editors - it seems to me if it simply continued to use the old method of a simulated click on the hoverPreviewTarget to close the popover (instead of explicit `hide()`), this would avoid closing Hover Editor while retaining the ability to not insta-close an active built-in editor.

**Comment by zsviczian** [comment]
@pjeby, my suspicion is also .hide() was introduced to hide the active built-in editor which got stuck on the screen.

The custom logic is there for two reasons (though I wrote much of this 2-3 years ago... so it is likely ripe for a review and rewrite - true for the entire plugin :))
1) To support Excalidraw full-screen mode, in which case I take hover preview out of the default DOM tree and place it under Excalidraw so it stays visible
2) to support positioning the hover preview on the canvas (though I am less sure why this was required)

**Comment by pjeby** [comment]
Yes, it's certainly to hide that, I was just saying the old click code should also work, but will not disrupt a pinned hover editor (i.e. one somebody moved), and should also fix the problem with only being able to have one active hover editor per Excalidraw view.

That is, it looks like the switch to hide() was mainly driven by adding logic to check if it's an active editor and leave it alone.  It should still do this check, but if the check fails then the simulated click should be used to close it.  (Or at least that is one option that would work.)

Another option would be to check if the popover's `.isPinned` property is true, and if so treat it the same as you do an active editor, i.e. drop your reference to it and return without further action.  (But this approach involves directly inspecting third-party state, which is why I suggested the other approach (i.e. sticking to clicking) first.)

Anyway, either of these approaches should keep it from closing an in-use hover editor, and would (presumably) re-enable the ability to have multiple hover editors active from different link points in the same diagram.

**Comment by zsviczian** [comment]
I added the following to the code in the `clearHoverPreview()` function. If the hoverPopover is a hover-editor then I revert to the old logic. I hope this solves the issue. I will release this update over the weekend.

```ts
  private clearHoverPreview() {
    //@ts-ignore
    const hoverContainerEl = this.hoverPopover?.containerEl;
    //don't auto hide hover-editor
    if (this.hoverPopover && !hoverContainerEl?.parentElement?.hasClass("hover-editor")) {
      this.hoverPreviewTarget = null;
      //@ts-ignore
      if(this.hoverPopover.embed?.editor) {
        return;
      }
      //@ts-ignore
      this.hoverPopover?.hide();
    } else if (this.hoverPreviewTarget) {
      (process.env.NODE_ENV === 'development') && DEBUGGING && debug(this.clearHoverPreview, "ExcalidrawView.clearHoverPreview", this);
      const event = new MouseEvent("click", {
        view: this.ownerWindow,
        bubbles: true,
        cancelable: true,
      });
      this.hoverPreviewTarget.dispatchEvent(event);
      this.hoverPreviewTarget = null;
    }
  };
```

**Comment by pjeby** [comment]
That fixed it, thanks!

**Comment by jiajiala** [comment]
Celebrate! Two of the best plugins can be used together again
