### ISSUE TITLE
FR: Timestamp-Based Image Naming with Copy and Paste Images

### ISSUE THREAD

**Issue by HoodyEz** [zsviczian/obsidian-excalidraw-plugin#2081]
### Is your feature request related to a problem? Please describe.

First of all, many thanks to Zsolt's for all the effort you’ve put into bringing the Excalidraw plugin to Obsidian and for continuously improving it over the years.

I’d like to know if there’s a way to change the names of the images inserted into Excalidraw with copy and paste. Images added through the toolbar or dragged and dropped retain their original names but when copied and pasted the images are assigned names like 'image', 'image_1', and so on, which can create conflicts with image names.

### Describe the solution you'd like

I was wondering if it would be possible to change the default name to include the date and time, just like the canvas naming format—e.g., 'Image 2024-10-27 14.29.30', 'Image 2024-10-27 14.29.31', and so on—or perhaps using unique codes like 'cedf943kfd' to avoid issues with WikiLinks.

### Real-life usage scenarios

For example, when I take notes at university, I sometimes want to add images like screenshots of PDFs. I tried using the Rename Images script, but I haven’t gotten used to it because I have to rename each image manually and move it to the appropriate folder, as it is saved by default in the Vault Root. Throughout the day, it becomes a bit tiring to have to rename the images every time, and I’d like to have an option for them to be renamed automatically.

### Additional context

[screen-capture.webm](https://github.com/user-attachments/assets/e7cd20f5-67cc-4991-b9b0-28c04ec1b517)
[screen-capture (1).webm](https://github.com/user-attachments/assets/71f2bb21-f5af-410e-84d2-d1a5c841da52)

**Comment by zsviczian** [comment]
yeah... that is because the image arrives via paste with the name image. If you copy paste an image that has a proper name (i.e. from a browser) then it will keep that name.
I could add some rules that you can configure which received names to override.
_1, _2, ... comes from the naming conflict

For PDFs instead of screenshots, I recommend using the PDF++ plugin. Watch this: https://youtu.be/LtuAaqY_DNc PDF++ area clipping will link your Excalidraw notes to the relevant page in the PDF without creating additional scrap files. It is simply a much better process overall for dealing with PDFs.

**Comment by zsviczian** [comment]
Fixed in 2.6.1 (at least for the case when the pasted image has a default name of "image.png".
