### ISSUE TITLE
BUG: Chinese fonts are not rendered in latex statements (probably due to latest updated refactoring of mathjax and local language font loading)

### ISSUE THREAD

**Issue by shisunsun** [zsviczian/obsidian-excalidraw-plugin#2162]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

macos 15.1.1
obsidian V1.7.7
Excalidraw 2.7.0

### Describe the bug

Chinese fonts are not rendered in latex statements
( excalidraw 1.6.8 works, but excalidraw 1.7.0 break down,  probably due to latest updated refactoring of mathjax and local language font loading)

### Steps to reproduce

clarify below:
![image](https://github.com/user-attachments/assets/36170104-dec0-44f6-a0c5-f2662312d17a)

### Expected behavior

<img width="627" alt="image" src="https://github.com/user-attachments/assets/9bfe9fdd-f991-40e6-870d-b1c07da3ebe5" />

**Comment by zsviczian** [comment]
I am able to reproduce. The issue is caused by changing from unescape to 

```ts
function svgToBase64(svg: string): string {
  return `data:image/svg+xml;base64,${btoa(
    unescape(encodeURIComponent(svg.replaceAll("&nbsp;", " "))),
  )}`;
}
```
to decodeURIComponent

```ts
function svgToBase64(svg: string): string {
  return `data:image/svg+xml;base64,${btoa(
    decodeURIComponent(encodeURIComponent(svg.replaceAll("&nbsp;", " "))),
  )}`;
}
```

because unescape is depricated.

I did not know that decodeURIComponent does not support non-latin characters. 
Will fix in 2.7.1

I'll wait until tonight, maybe tomorrow to release the fix to see if other problems surface as well and I can fix them all in one go.
