### ISSUE TITLE
Failed to load plugin obsidian excalidraw-plugin

### ISSUE THREAD

**Issue by sissi815zx** [zsviczian/obsidian-excalidraw-plugin#244]
**Describe the bug**
When open obsidian , the warning “Failed to load plugin obsidian excalidraw-plugin” appear.
![image](https://user-images.githubusercontent.com/35757538/141464687-592ce12a-cc9e-4c20-92cf-401ffdaef5bc.png)
No Excalidraw icon
![image](https://user-images.githubusercontent.com/35757538/141464903-6a9f668d-9775-446f-80b7-d776476dd995.png)

windows 10
Excalidraw 1.4.7

**Comment by zsviczian** [comment]
This is typically due to an old version of Electron browser running under obsidian. Solution is to uninstall Obsidian and reinstall using the latest install pack.

If you press CTRL+SHIFT+i you can bring up the developer console.
execute `process.versions.electron` if the result is version 8 or 9, you definitely have this root cause.

Here's mine:
![image](https://user-images.githubusercontent.com/14358394/141505946-8e4e0c75-d9b7-49b0-af67-4f5684b23b62.png)

**Comment by zsviczian** [comment]
did reinstalling Obsidian solve the problem for you?

**Comment by zsviczian** [comment]
closing as I received no response. I believe the above should have resolved your issue. If not, please reopen this.
