### ISSUE TITLE
Script store won't open for me.

### ISSUE THREAD

**Issue by DamnedScholar** [zsviczian/obsidian-excalidraw-plugin#336]
**Describe the bug**
I can click on the gear to open the script store, but it opens a modal with no content inside the div. There's a console log that might indicate a cause, in the screenshot section.

**To Reproduce**
1. I have just installed Excalidraw.

**Expected behavior**

**Screenshots**
https://i.imgur.com/1QlWQr2.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.13.14

**Comment by zsviczian** [comment]
hm... the error message does not help.
Can I ask you to restart Obsidian and try again? Though, I don't know why it would help...
I have experienced short outages with GitHub in the past... maybe the issue is related to that, I will add some error handling for such cases. That said, the error message is also strange.

Does the Excalidraw plugin otherwise work for you?

Does this link open for you without any issues?
https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/ea-scripts/index.md

**Comment by DamnedScholar** [comment]
As of trying it tonight, I'm able to access the script store with no issues. So it's definitely a "try again later" issue. I don't remember if I restarted Obsidian between tries, because I gave up and moved on to drawing. I will try that link if I hit a persistent load issue again, because it's possible that it was just `githubusercontent.com` or whatever CDN lies behind that having a loose connection to the rest of the Internet. 🤷🏻

When I was hitting that snag, the rest of your plugin performed fine and the GitHub app itself was obviously making it to me.
