### ISSUE TITLE
iPad text input from keyboard causes canvas jump on deselect

### ISSUE THREAD

**Issue by unfamiliarish** [zsviczian/obsidian-excalidraw-plugin#354]
**Describe the bug**
Deselecting after editing text box causes canvas to jump, centering all content.

**Expected behavior**
The canvas would not jump after text deselect. Does not occur on excalidraw.com.

**Environment**
- iOS 15.1 (2020 iPad Pro 12.9")
- Obsidian v1.0.5
- Excalidraw v1.5.16
- Logitech Combo Touch iPad Pro (5th gen)

**Video**
https://www.dropbox.com/s/6xbbd4m8qq2ndol/excalidraw_obsidian_ipad_text_canvas_jump.mp4

**To Reproduce**
* In Obsidian:
  * Using keyboard trackpad, double-click, add text using keyboard, click off (jumps)
  * Using apple pencil, double-tap, add text using keyboard, tap off (jumps)
  * Using finger, double-tap, add text using keyboard, tap off (jumps)
* In excalidraw.com:
  * Using keyboard trackpad, double-click, add text using keyboard, click off (does not jump)
  * Using apple pencil, double-tap, add text using keyboard, tap off (does not jump)
  * Using finger, double-tap, add text using keyboard, tap off (does not jump)

**Comment by zsviczian** [comment]
Yes, this is a known issue, and is caused by the on-screen keyboard (even if you are using an external keyboard, the screen will resize when you start to type).

As a temporary solution please disable zoom to fit on resize in settings.

![87288409-83BC-49B5-9148-5387190A9654](https://user-images.githubusercontent.com/14358394/149291509-5b0b9c5a-5f2a-4e3b-a25e-386d08772ecd.png)

**Comment by unfamiliarish** [comment]
Excellent thank you! I wasn't previously aware of the plugin settings in obsidian. Thank you for all your recent help!
