### ISSUE TITLE
Add "line" to the Darken & Lighten background color scripts

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#370]
Hi @1-2-3,

I suggest modifying 
- Darken background color
- Lighten background color

Adding line to the filter, since lines can form closed objects as well.
```javascript
const elements = ea
  .getViewSelectedElements()
  .filter((el) =>
    ["rectangle", "ellipse", "diamond", "image", "line"].includes(el.type)
  );
```

What do you think?

**Comment by 1-2-3** [comment]
Good suggestion, I have submitted the PR.

**Comment by zsviczian** [comment]
Hi @1-2-3, I am planning to publish a short video to my channel showcasing the scripts currently available in the script store. I'd like to give credit to you in the video. With what name can I refer to you? Also, if you don't mind sharing your twitter and discord handle, I'd use those to give credit when I tweet / post about the new video.

**Comment by 1-2-3** [comment]
Very happy to contribute some useful features to the community. I am a full stack software engineer in China. My name is Jing ChunLei, you can call me Jing for short. And I don't have a Twitter account, as well as Facebook and Instagram... Because of the great firewall... In fact, Excalidraw.com is virtually inaccessible in China. It's your plugin that makes it easy for us to use Excalidraw and integrate drawings with documentation so easily, as well as add tags and aliases to drawings. Now I try to use Obsidian and Excalidraw plugins to write and manage almost all of my working documents.
