### ISSUE TITLE
Excalidraw doesn't create new files in specified folder

### ISSUE THREAD

**Issue by aadimator** [zsviczian/obsidian-excalidraw-plugin#373]
**Describe the bug**
When I use the command `Create a New Drawing - IN A NEW PANE - and embed into active document `, it places the created Excalidraw file in the default attachments folder as opposed to the one specified in the Excalidraw settings.

![image](https://user-images.githubusercontent.com/10383542/150266150-bef163ed-2be2-4141-8cac-03294ed3bb52.png)
Excalidraw settings

![image](https://user-images.githubusercontent.com/10383542/150266392-339aca32-4cf4-4eb3-a08e-68f33f7e67c5.png)
Default Obsidian settings

![image](https://user-images.githubusercontent.com/10383542/150266458-a386621c-b5f7-45e8-b468-c100ef575df6.png)
All files are placed in the default "Attachments Directory".

![image](https://user-images.githubusercontent.com/10383542/150266678-6dce09ea-8367-4e27-9aa0-64059d39a132.png)
"Excalidraw" folder has only the files that I manually placed there (By right-clicking on the folder and choosing "New Excalidraw drawing"

**Expected behavior**
It should place the newly created files in the folder specified in the "Excalidraw Settings", not the default Attachments directory.

**Desktop:**
 - OS: Windows 11

**Comment by zsviczian** [comment]
Yes, I recognize this is a little confusing. I should really add some additional settings.

When you embed a drawing into an `.md` file with the command palette action `Create a New Drawing - IN A NEW PANE - and embed into active document` I place the drawing in the attachments folder specified in Obsidian settings. 

![image](https://user-images.githubusercontent.com/14358394/150581782-a67258f9-0455-478d-9669-073b0c7e41a4.png)

When you create a new drawing using the ribbon button, or the command palette action `Create a new drawing - IN A NEW PANE` then, because I don't have a host `.md` document, I create the drawing in the excalidraw folder specified in settings.

I could add a toggle to set that the excalidraw folder setting applies also to files embedded using the `...and embed into active document` action.

**Comment by aadimator** [comment]
Yeah, the toggle would be great. That way I could have the option to store all of the Excalidraw files in a specific folder.

**Comment by zsviczian** [comment]
I added a toggle in 1.5.20. I will release it later today

![image](https://user-images.githubusercontent.com/14358394/150632874-a39526db-6782-4048-b289-a11d494c82f7.png)
