### ISSUE TITLE
Add option to embed using shortest path

### ISSUE THREAD

**Issue by riddyrayes** [zsviczian/obsidian-excalidraw-plugin#405]
**Describe the solution you'd like**
Add an option to embed using a link with shortest possible path when using "Create a new drawing, open in a new pane and embed it"

**Is your feature request related to a problem? Please describe.**
The present command links the whole path of the file.

**Describe alternatives you've considered**
Maybe using a Templater script, but its best if this could be built in.

**Additional context**
I actually move around my notes from folders and also keep my note titles unique. So it would be best if the embed links would just contain the file name when creating them.

**Comment by zsviczian** [comment]
Sure, I can do this. In the past, I added the link to the document before the drawing file was created, thus the current solution. With live preview, I had to change the process, otherwise, embeds did not show up correctly. Should be possible now without any difficulty. I will simply follow the Obsidian system setting.

**Comment by zsviczian** [comment]
will be released with 1.5.29 today
