### ISSUE TITLE
Hover preview of Excalidraw documents not working

### ISSUE THREAD

**Issue by fwiesbauer** [zsviczian/obsidian-excalidraw-plugin#416]
When hovering over the Excalidraw notes in the file explorer or over the link to an Excalidraw file in a markdown note, the preview is not working:

https://www.loom.com/share/68e7971f430a4b018370375caec9a55e

**Comment by zsviczian** [comment]
hm. this is strange.
Does `![[Drawing-Chief Marketing Officer Orgchart]]` display an image in live preview editing and reading modes?
Do you see any errors in Developer Console (CMD+i)?

![image](https://user-images.githubusercontent.com/14358394/152855793-fbfbf086-4661-441f-859f-e11e853c9e6b.png)

**Comment by fwiesbauer** [comment]
As to your questions:

"Does ![[Drawing-Chief Marketing Officer Orgchart]] display an image in live preview editing and reading modes?" 

Answer is: same behavior in both instances...no live preview image available.

"Do you see any errors in Developer Console (CMD+i)?"

Answer: CMD+i creates "**" in my case. Not exactly sure how else to invoke this Develpoer Console.

**Comment by zsviczian** [comment]
my mistake it is `cmd+ option + i`

**Comment by fwiesbauer** [comment]
Same thing, no preview.

**Comment by zsviczian** [comment]
`cmd + option + i` will not solve the preview, but it should bring up the developer console so you can see if there are any error messages popping up when you try the hover preview. If there are, I'd need a screenshot of those errors.

**Comment by fwiesbauer** [comment]
I don't see an error message. 

Does this screenshot help?

![2022-02-08 at 16 57](https://user-images.githubusercontent.com/75667224/153025585-917e9f60-d33e-448b-a094-89cb46f2e580.png)

**Comment by zsviczian** [comment]
I also don't see any error messages. 
This could be a styling issue. Or an issue caused by another plugin. Or anything else :)
So unfortunately we'll need to do some debugging together.

I see these first two steps:
1) 
Turn off all the other plugins and see if Excalidraw previews work. If yes, then turn them back on one by one and see when it stops working... and we know our culprit.

2)
If 1) does not yield a solution, we'll need to do a bit of debugging. I created a short screen recording of what you need to do.
- key steps: notice I first switch to the "Sources" tab, and observe the shortcut for pausing the script.
- When I then bring up the hover preview, I press "CTRL+\" the shortcut I observed in the previous step. The developer console will try to bring up the line of code where it stopped. This can take a while.
- Once Developer Console is responsive again I navigate to the "Elements" tab, and scroll to the bottom. I am looking for a screenshot of the "popover hover-popover is-loaded" element. Something like this:

![image](https://user-images.githubusercontent.com/14358394/153056833-a76ed4fc-dfc5-43f3-859b-b9c211bc3575.png)

**Comment by faerch90** [comment]
I have the same issue.
I get the following error message.

![image](https://user-images.githubusercontent.com/65782471/153160642-58b5aa95-0d03-4194-a2e4-3412f897a6de.png)
![image](https://user-images.githubusercontent.com/65782471/153160814-772b337d-ef06-4882-8582-c8b94bde3a3c.png)

Maybe the hyperlink is messing with ankiconnect in some way. 
I have a couple of anki plugins installed, I will try to identify the culprit later.

**Comment by zsviczian** [comment]
Seems I forgot to attach the screen recording...

https://user-images.githubusercontent.com/14358394/153656185-c42a450a-4d55-4695-90d5-1de4aaffb53e.mp4

**Comment by fwiesbauer** [comment]
I really appreciate your effort Zslot but this is above my paygrade. But never mind. Your Excalidraw plugin is great even without the preview 👍  🙏🏻

**Comment by zsviczian** [comment]
if you have time we can try desktop sharing in discord. are you available at any time tomorrow?

**Comment by fwiesbauer** [comment]
Sure. That would be amazing. I'll send you a ping.
