### ISSUE TITLE
Script Repository  not loading. 

### ISSUE THREAD

**Issue by thecookiemomma** [zsviczian/obsidian-excalidraw-plugin#417]
**Describe the bug**
Due to either adding more plugins or due to the new pre-release version (0.13.24) of Obsidian (or some combo thereof), I am no longer able to open the script library. 

**To Reproduce**
1. Go to an excalidraw  drawing. 
2. Click on the script engine button
4. See error "unable to load scriptrepository engine" popup error.  When I look at the dev console, the commentary says, "Cannot load null."  

**Expected behavior**
Open up the script repository and see the scripts. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox

**Additional context**
![image](https://user-images.githubusercontent.com/15720918/152898774-deda923f-3c1b-45e4-b060-757006e624cc.png)
(Posted twice cuz I accidentally grabbed two errors of the same thing).

**Comment by zsviczian** [comment]
The error message does not look familiar. Also, when you open the script library I am loading the list of plugins from GitHub, not your local vault, but the error seems to be related to accessing a file locally in the vault (e.g. the mention of basename). I am guessing this could be potentially caused by another plugin. Unfortunately, the only way to find out is to turn off all the other plugins, restart Obsidian, and turn the plugins back on one by one, all the time testing to see if the script library opens or not.

**Comment by thecookiemomma** [comment]
Used the excellent Divide and Conquer strategy and discovered it was not EXCD at all, but "Image Captions" causing the issue. Thank you.
