### ISSUE TITLE
Wasted space on iPad

### ISSUE THREAD

**Issue by Signynt** [zsviczian/obsidian-excalidraw-plugin#450]
On iPad the UI has quite a bit of space from the edge of the screen, which wastes a lot of precious screen real estate.
I've attached a screenshot taken in tray-mode.

![image](https://user-images.githubusercontent.com/67801159/154535129-d6f86e12-f556-480f-9abb-06f3fdae9613.png)

**Comment by zsviczian** [comment]
Some of this you can address with css snippets. But the longer-term solution is to implement fullscreen mode for the ipad.
The padding at the bottom is due to the iOS keyboard (the horizontal line), then a large bottom padding by Obsidian, and only then excalidraw. If you switch your drawing to dark mode you will see the sapece Excalidraw takes up, vs. the environment.

**Comment by zsviczian** [comment]
Looking at the two screenshots, you may want to experiment with other Obsidian themes, to see if that has an effect. On my screenshot the toolbox and the tray looks smaller, than on yours...

**Comment by zsviczian** [comment]
To help with your situation I just published a new Excalidraw script to the script library. Please install `Toggle Fullscreen on Mobile` script. You can access the new command from the command palette after installation. 

If you want to use the Customizable Page Header buttons plugins to add Excalidraw commands to the header (like on my screenshot), then you can open Excalidraw settings and disable the hiding of the header buttons when going full screen.

**Comment by Signynt** [comment]
The fullscreen mode already helps, I'll see what other improvements I can do with some css snippets specifically for this theme ([Primary](https://github.com/ceciliamay/obsidianmd-theme-primary)). Is there any documentation on customising the css of Excalidraw for themes?
