### ISSUE TITLE
Unable to visualize when I draw or insert an object.

### ISSUE THREAD

**Issue by ajaygunalan** [zsviczian/obsidian-excalidraw-plugin#46]
Hi,

Kindly check this [screen recorded video ](https://www.youtube.com/watch?v=6pVzYHDp0ek) where I'm unable to visualise the content while I draw. Is there any scaling factor which I should set?

**Comment by zsviczian** [comment]
Thanks! I was able to reproduce the issue. Based on my quick testing, this only happens when you create a new drawing on a new pane when your active pane is another excalidraw drawing. If you chose Create new drawing in CURRENT ACTIVE PANE, the issue does not happen. The issue also does not occur when your active pane is a markdown document and you chose to create new drawing IN A NEW PANE

I will fix this in the next release. Until then, start new drawings when you active pane is an .md document, or use create new drawing in CURRENT ACTIVE PANE

**Comment by zsviczian** [comment]
Also this issue seems to be limited to sliding panes. I can't reproduce the issue with the default workspace setup.

**Comment by ajaygunalan** [comment]
Thank you so much for the immediate response. I'm glad that I could find bug for you. 
This plugin is super awesome, I was able to draw neat circuits using this. Thank so you much for your efforts and your YouTube videos are really helpful.  I shared your videos with my friends and they were super excited too!

**Comment by zsviczian** [comment]
Here's 1.0.8-test3. It resolves this issue as well. Please help with testing.
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.8-test3

**Comment by zsviczian** [comment]
1.0.8 release solves this
