### ISSUE TITLE
Automatically update links on ExcalidrawElements when internal file names change

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#546]
I can click on an element in an Excalidraw document and select "create link".  I can then enter [[filename]] and this adds a link from this element to the named file in the element.link property.  If I then rename the file the value in the link property is not updated with the new name whereas any other links to the file in markdown documents are updated.  Is there any way to have these links automatically updated to reflect file name changes in the same way.

**Comment by zsviczian** [comment]
Thanks!

The link technically does update... but I wonder why the drawing does not reload when the link is opened in a neighboring leaf since it should reload on `app.vault.on("modify",  (file)=>{})`. 

https://user-images.githubusercontent.com/14358394/159977326-8b8a370a-fcb5-4a5a-980c-a74955f042e6.mp4

**Comment by zsviczian** [comment]
Turns out there were two bugs. I was using `app.vault.cachedRead()` in the `vault.on("modify"` trigger, and it seems page caching and the firing of on modify are in a race condition. The other bug was simply my own stupidity but now resolved.

I will release the fix over the weekend. Thanks!

here's the fixed main.js, should you want to use it before the release comes out in a few days.
[main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8345068/main.zip)
