### ISSUE TITLE
Organize obsidian pages as images

### ISSUE THREAD

**Issue by RickHurts** [zsviczian/obsidian-excalidraw-plugin#557]
**Is your feature request related to a problem? Please describe.**
Cannot add image elements if the total image elements exceeds 2 mb.

**To Reproduce**
1. Add image element that will let the total image elements on a page memory size exceed 2 mb. 
2.  Error message: Error, File is too big. Maximum allowed size is 2MB.

**Describe the solution you'd like**
As a visual thinker, I want to use obsidian in a way that pictures organize the complex mess of pages.
In my eyes obsidian and the excalidraw-plugin together have the potential to do this. But what it lacks at the moment are:
- the ability to add the preview image of another page (ctr + hover over title) in obsidian as a image element in the excelidraw-plugin
- option to add more than 2mb of image elements on one page (for example setting to adjust maximum size of total image elements on a page with maybe a warning message of the expected drawbacks)
- using the https://pngquant.org/ open source script to reduce the size of .png files

**Describe alternatives you've considered**
reducing image size using pngquant (see above)

**Additional context**

**Environment (please complete the following information):**
 - Windows 11
 - Plugin version: 1.6.21
 - Obsidian version: 0.14.2

**Comment by zsviczian** [comment]
The size limitation is in the Excalidraw package, because larger files would obstruct the collaboration feature of Excalidraw.
I can look into if I can remove this limitation. BTW you only get this error if you paste an image into Excalidraw directly. If instead you first save the image to your vault and then insert the image using the command palette action "Insert Image from Vault", then you can insert any size of an image.

**Comment by zsviczian** [comment]
I increased the file size limit to 20MB in 1.6.22. I will release the new version possibly today.

**Comment by RickHurts** [comment]
Thanks, great!
