### ISSUE TITLE
Latex Math Duplicates: original object changes after editing duplicate object

### ISSUE THREAD

**Issue by linuswalter** [zsviczian/obsidian-excalidraw-plugin#593]
For creating a new latex math object, I usually duplicate an existing latex math object (via `alt`+ `drag object`) because it is the fastest way for me.
When editing the duplicate (`ctrl` + `left click` -> edit mode)  and saving the edit (`enter`), Excalidraw renders/changes the original latex math object and not the duplicate.

Maybe this is easy to fix :)

Best, Linus

PS: Thanks again for the awesome work Zsolt. I will buy another coffee!

Obsidian version: v0.14.6
Excalidraw version: 1.6.25

**Comment by linuswalter** [comment]
Thank you for your answer :heart_eyes: . TheBrain-navigation sounds really good!

Just one relevant thing to add about the Latex Issue:
When I `copy`+ `paste` a Latex math object, the bug does not occur.

Linus

**Comment by zsviczian** [comment]
I'll do some debugging to understand what is going on. Copy+Paste vs. Alt+drag is interesting, though the two work slightly differently. There is an event handler for onPaste where I can insert my own code without modifying the core Excalidraw package, while Alt+drag happens completely inside Excalidraw. I'll need to take a look at the code, maybe copy/paste works because I implemented a change a few month ago... I remember this issue has come up in the past already.

**Comment by zsviczian** [comment]
I fixed this in 1.6.26. I will release it later tonight or tomorrow.
