### ISSUE TITLE
Test to embed different parts of the same markdown failed !

### ISSUE THREAD

**Issue by pterusgithub** [zsviczian/obsidian-excalidraw-plugin#601]
**Describe the bug**
Let's say that we have a markdown like this:
># Heading 1
>blablabla
>
># Heading 2
>bliblibli

Let's say that we want to embed the H1 and H2 parts in separate frames inside the same drawing ... It misses ...

**To Reproduce**
1. Ctl click on a markdown
2. drag and drop the markdown on the drawing
3. Alt + Ctl + click on the markdown page within the drawing
4. add # **Heading <u>1</u>**(save or wait or whatever you want ...) giving you a **blablabla** embedding (perfect!)
5. reproduce the steps with heading 2 meaning:
    a. Ctl click on the same markdown
    b. drag and drop the markdown on the drawing
    c. Alt + Ctl + click on the markdown page within the drawing
    d. add # **Heading <u>2</u>**  to obtain a second blabla embedding (not a **bliblibli** one ...)

**Environment (please complete the following information):**
 - OS including version: Ubuntu 18.04.6 LTS
 - Plugin version: 1.6.25
 - Obsidian version: 0.14.6

**Comment by zsviczian** [comment]
Thanks for raising. I am able to reproduce this.

This has the same root cause as #593 (the underlying file ID is the same for the same file / object). I have some thoughts on how to solve this.

I'll try to get to this in the coming days... though at the moment my normal day job is busy, and I am working on ExcaliBrain... thus it may end up taking a bit longer to resolve this than normally.

You can apply a workaround. See video:

https://user-images.githubusercontent.com/14358394/165701695-f5566569-3781-46cd-b815-e1e871fb880e.mp4

**Comment by zsviczian** [comment]
I fixed this in 1.6.26. Will release later tonight or tomorrow.

**Comment by pterusgithub** [comment]
Thx !!! :-)
