### ISSUE TITLE
Better Dataview field support

### ISSUE THREAD

**Issue by erichalldev** [zsviczian/obsidian-excalidraw-plugin#633]
I would like to be able to define Dataview link fields in an Excalidraw drawing (e.g. in a sticky note) without having to modify the file in Markdown mode. This has a significant impact on how I use Excalibrain. In order to define an Excalibrain link field (e.g. Parents, Friends), I have to insert the Dataview field in Markdown mode. Being able to define these fields in drawing mode would not only save me a lot of time, but it would also be more obvious which Excalibrain connections are defined because they would be visible in the drawing. 

I investigated how Dataview indexes the values for fields defined in both Markdown and Excalidraw mode. In drawing mode, it appears that Dataview finds four separate instances of the field name (e.g. Parents), but it doesn't determine that any of them are a link. I'm guessing this because the Excalidraw drawing stores that drawing text in four different places, and all of the quotation marks and block reference annotations inhibit Dataview from properly finding the link. However, in Markdown mode, it finds just a single instance of the field and correctly determines that it's a link.

Here's a drawing I created to illustrate the issue:

![image](https://user-images.githubusercontent.com/5632228/169856610-896cc856-82bf-46b4-9963-7bcc67fdf551.png)

Thank you so much for the Excalidraw and Excalibrain plugins! They are completely changing how I take notes, in the best way possible.

**Comment by zsviczian** [comment]
Very interesting.

I did not notice this issue because I am always using Excalidraw with compressed JSON. Try to turn on this setting. It will solve your issue.

![image](https://user-images.githubusercontent.com/14358394/169866928-0b53d35c-4a6b-400b-82c0-07c1e98ce7b8.png)

However, I will also look into why without the compressed JSON this is not working. Compressing the JSON should not make any difference to Dataview since the JSON is in a code block and "Parents::" is between quotation marks in the JSON.

**Comment by zsviczian** [comment]
This will be solved in excalibrain 0.0.13. Though for performance and for Obsidian search experience, I still recommend using compressed Excalidraw files.

It might be just a DataView bug, but with this change, you will also be able to use inline fields mid-way through a paragraph. Looks very useful, though the jury is still out if this is a [feature or a bug in DataView](https://github.com/blacksmithgu/obsidian-dataview/discussions/1111)

![image](https://user-images.githubusercontent.com/14358394/170096626-85ef0cbb-82ed-41e3-99ad-0ffd78762c1d.png)

**Comment by erichalldev** [comment]
I enabled compressed JSON and it worked well, thank you for the suggestion. Something I noticed: if a new line is added after a DataView field in Excalidraw, DataView parses it as a link. If a new line isn't added after, it defines it as a string. I think this is because of the block identifier (^kMqdGRnJ). Interestingly, ExcaliBrain picks up both of them just fine as a link.

Without a trailing new line:
![image](https://user-images.githubusercontent.com/5632228/170108794-7fe12ac8-0293-4a16-a5c0-d4f3aae577be.png)

With a trailing new line:
![image](https://user-images.githubusercontent.com/5632228/170108744-0950128d-9e76-4bbf-b5c7-fb59c0045681.png)

**Comment by zsviczian** [comment]
Indeed ExcaliBrain will pick the links from any DataView field. This is because I like to embed links within paragraphs of text:
`j:: The links in this [[paragraph]] are all friends of the [[host]] note.`

In 0.0.13 I will also pick links from YAML fields - though personally, I don't prefer adding links to YAML because Obsidian does not update those when I rename filese.
