### ISSUE TITLE
Excalidraw can't save.  

### ISSUE THREAD

**Issue by eyeojo** [zsviczian/obsidian-excalidraw-plugin#658]
Apologies for being redundant, I just left this issue over on the Obsidian Forum but realized this is more appropriate.  I don't see any other reference to this issue that I am having, but it prevents me from working almost immediately - with an error pane that ends up looping: 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/9010880/173168939-2afc26e2-1976-4e29-93c9-a070557e428e.png">

Figured this out.  This was only happening when I used images.  They weren't being saved to the specified Attachments folder correctly because I had the folder name in CAPS.  Obsidian had been able to figure this out apparently, but Excalidraw through up the error.  Seems to be working great now, but thought you would like to know!  Thank you for this Plug-in!
____

**Comment by zsviczian** [comment]
Thanks for opening this issue. Just so I can address this edge case properly. Which folder name did you have in CAPS? The attachments folder in settings, the folder in your vault where the images were, or?

**Comment by eyeojo** [comment]
Hi Zsolt, thank you.  My Attachment folder path in settings had been in caps, specifically "BINS/Images".  The folder in my vault is "Bins/Images".

**Comment by zsviczian** [comment]
Thanks.  I added some error handling to the code to handle this situation.

As a general recommendation, you should always assume that file paths are case-sensitive. On Windows they are not, but on many other platforms e.g. LINUX, iOS, etc. they are. If you synchronize your vault to one of these or try to use links outside Obsidian (apparently, Obsidian has built some "safety net" for case-sensitive filenames) you might find that your links are broken because of the letter case.

I will release the fix in 1.6.34.


On the bright side, my obnoxious warning about not being able to save the file worked. It caught a situation the plugin was not able to handle.
