### ISSUE TITLE
Ozan's Image in Editor plug-in - Excalidraw drawing appears twice after editing the drawing (in a new pane)

### ISSUE THREAD

**Issue by bwydoogh** [zsviczian/obsidian-excalidraw-plugin#66]
**Describe the bug**
Using the plug-in together with "Ozan's Image in Editor" plug-in. When editing a drawing, embedded in a note, in a new pane... the drawing appears 2 times in the note after editing the drawing (and closing the drawing). Editor mode.

**To Reproduce**
1. Open a note which embeds a drawing
2. Open the drawing in a new pane (_pay attention: I am using the "Sliding panes" plug-in_)
3. Edit the drawing
4. Close the drawing 
5. Check the note (in editor mode): the (edited) drawing appears 2 times

**Expected behavior**
The drawing appears once.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
Sliding panes plug-in.
Latest version of all plug-ins.

**Comment by zsviczian** [comment]
Hi! Thanks for raising, however, this is something you need to raise with Ozan. 
https://github.com/ozntel/oz-image-in-editor-obsidian/issues

**Comment by bwydoogh** [comment]
OK, done (https://github.com/ozntel/oz-image-in-editor-obsidian/issues/24)

**Comment by bwydoogh** [comment]
Hello @zsviczian. After further investigation (see comments https://github.com/ozntel/oz-image-in-editor-obsidian/issues/24): it happens when I turn on the setting "Auto-export PNG" (turning it off = all fine; turning it back on = problematic). So it does seem to be related to this plug-in.
Could you have a look please? Thanks.

**Comment by zsviczian** [comment]
Thanks for the investigation. This is very interesting. I will investigate.

**Comment by ozntel** [comment]
Hi @zsviczian I suppose I found a solution for this issue. 

Due to fact that each save triggered 2-3 image changes (svg, png, excalidraw), my plugin couldn't manage removing previous widget and included an additional one on the top of the previous one. 

I am including now an additional check to ensure that only the image updated is refreshed in the editor. 

@bwydoogh before I release a new version, could you please download the new `main.js` from my repo and try if it solves your problem? I just pushed the version with fix.

**Comment by bwydoogh** [comment]
@ozntel Fixed! Thanks a lot!
