### ISSUE TITLE
Self-Hosted Excalidraw URL

### ISSUE THREAD

**Issue by scottrbaxter** [zsviczian/obsidian-excalidraw-plugin#666]
**Describe the solution you'd like**
I understand that excalidraw.com currently provides free usage, but given Excalidraw itself can be hosted by anyone, it would be great to have a setting in this plugin to specify a URL for self-hosted instances of Excalidraw.

**Additional context**
With the latest version of this plugin, I'm not able to find a section in the settings to specify an Excalidraw URL. Any chance this would be an easy addition?

Thanks for supporting this plugin and connecting these services!

**Comment by zsviczian** [comment]
What problem do you want to solve by self hosting?

**Comment by rennhak** [comment]
Great work with the plugin, really awesome and well done! 
Thank you for all your time and effort @zsviczian !

-----

In regards to this feature request, I'm interested in this too.

Reasons why this makes sense to answer your prior question:

### Ability to operate fully offline

No connectivity, no problem, still be able to operate by running excalidraw locally on my machine (ie. local docker). That way I can stay productive even w/o internet connectivity (eg. train, flights, camping, remote sites, bad connectivity sites, etc pp.)

### Future proof

The spirit behind having data in a format that is simple and accessible (ie. markdown) is that it will outlast us. By allowing me to run the excalidraw end point locally or self-hosted I am in control of my destiny and can ensure that in 10 or 50 years it doesn't matter if exaclidraw.com still exists or gets M&A'ed by an corporate that is not so friendly (think Oracle and Sun Microsystems products).

### No Vendor Lock-in

Obsidian with its PKM notion locally tries to avoid / remedy the issue of 3rd Party data centralization and data ownership/licensing. True, the exacalidraw format is not widely documented, but I hope that in the future it will become more inter-operable as a standard data format instead of a locked in corporate playground.

### Enhanced privacy

I own my .md files without sharing it with an 3rd party by choice. Why not allow certain users who want this to do so too via locally/self-hosted excalidraw? A certain amount of Excalidraw is by its nature open on github. I do not want to care what the T&C's are on Excalidraw.com and how my data is stored, secured or accessed.

**Comment by zsviczian** [comment]
@rennhak, I have good news for you. The Excalidraw Obsidian plugin is already 100% offline. There is no server, just Obsidian and the Excalidraw plugin script. All the required libraries are included in the main.js file. If you do not synchronize your Obsidian Vault, your data will never leave your PC. If you want a real future proof solution you can also configure the Excalidraw plugin to always auto export a PNG or SVG copy of your drawings, thus if for some reason Obsidian and Excalidraw stop to exist, you can still read your markdown files and view the PNG or SVG images. Please read through the settings, there are many related options to fine tune saving of images in a future proof manner.

The only exception from the offline availability are the LaTeX libraries (for math formulas). These are currently not included in the main.js plugin package… but even these could be packaged without much hassle, but I haven’t had the time or interest to work on that yet.

If you want to self host Excalidraw, it is fully open source, you can download all the necessary code from GitHub and host it / build it for yourself.

**Comment by rennhak** [comment]
Nice!

I assumed wrongly and thought this links back to the mothership to provide functionality, but alas its a fatlib.

I should have done some light digging in `package.json` before I messaged. It shows that it loads your exaclidraw fork `"@zsviczian/excalidraw": "0.11.0-obsidian-25"` into the plugin.

Apologies for the hassle, please consider this ticket closed.

**Comment by diimdeep** [comment]
@zsviczian Might not hurt to mention that this is offline solution, and it is not loading online service in an iframe, this is first question I tried to answer, it is also a good selling point.
