### ISSUE TITLE
Suggest adding [[]] link comments

### ISSUE THREAD

**Issue by MILKMILKKING** [zsviczian/obsidian-excalidraw-plugin#72]
It is suggested to add the function of [[ ]] linking notes, it would be very useful if you can insert [[ ]] notes in the drawing as well!
The biggest feature of obsidian is the two-way link, currently Excalidraw is very good, but can only achieve the function of drawing, if you can enter [[, it is like linking notes in obsidian's notes, it will greatly improve the usefulness of Excalidraw. For example, I sometimes have a lot of related notes about a note, if I can use Excalidraw, it is a great way to organize the related notes in a drawing board, connect them with lines, or note some ideas.

**Comment by zsviczian** [comment]
You can already enter links, albeit without the `[[ ]]`. 
https://youtu.be/FDsMH-aLw_I

I understand the feature is extremely basic at the moment, but taking it to the next level raises a number of dilemmas that I don't have a good solution for.
- Keeping links updated when filenames change: this will impact your drawing as the length of the text will change
- Since drawings are not markdown files, I don't have a good solution to show backlinks to drawings
- Would be ideal if you could insert a link by typing [[ and then choosing from a dropdown. It is not trivial to bring this function into Excalidraw.

I'll play with this a bit to see how I can further improve.

**Comment by zsviczian** [comment]
see release 1.1.8

**Comment by MILKMILKKING** [comment]
I have updated to version 1.1.8, but I don't see the option: Excalidraw: Insert link to file in the command options panel. I watched your youtube video of the update, it's great!
Also, after the update, the color palette panel on the left side of the drawing board is blocking the interface a bit. Can I hide this panel?

**Comment by zsviczian** [comment]
Do you have the kanban plugin installed? I just raised an issue with Kanban. The new update of the Kanban plugin kills the command palette for Excalidraw. https://github.com/mgmeyers/obsidian-kanban/issues/164

**Comment by q7z** [comment]
Are there any plans on bringing the suggester into Excalidraw?

**Comment by zsviczian** [comment]
that would require a more invasive change to core Excalidraw package... which I want to avoid to ensure Obsidian can benefit from the continued development of Excalidraw.

There is a command palette action to insert links. You can also drag and drop pages from the file manager. Plus you can open Excalidraw in a parallel window in Markdown-view mode and use that to change/edit text elements including links.  I know these are not perfect solutions, but on the mid-term I don't yet see a better approach, without impacting backward compatibility with the core Excalidraw product.
