### ISSUE TITLE
Graph view and link text bug

### ISSUE THREAD

**Issue by neKmaI** [zsviczian/obsidian-excalidraw-plugin#725]
I still working on my English. But I have a screenshot that will explain anything.
![Screenshot_2022-08-01_12_31_34](https://user-images.githubusercontent.com/18555566/182299202-c2c20164-e459-48ba-abf3-a7511b4d4ea9.png)
OS: Debian Linux
Obsidian: Flapak version 0.15.9
Obsidian-excalidraw-plugin: 1.7.9

Thank you Zsolt for this plugin and the teaching

**Comment by zsviczian** [comment]
Not a bug. This is how Obsidian works:
![image](https://user-images.githubusercontent.com/14358394/182365583-14e88329-c2ea-4a1d-a73b-12d768f8b8ab.png)

![image](https://user-images.githubusercontent.com/14358394/182367439-9f98b5ce-37fb-4d3f-8c3e-5dbe89555417.png)

For the 4th example see this discussion: #692 
In short, using the link button on text elements is not fully supported, because there would be a conflict between the link in the text and the link added with the button. Also note that if you use the fourth option, the link will not be updated when you rename the file. As a final note, if you add a link to a rectangle, or ellipse, or other non-text element those links will work properly and will also be updated when files are renamed.
