### ISSUE TITLE
Using emoji toolbar inside sketch throws an exception

### ISSUE THREAD

**Issue by pikatwinky** [zsviczian/obsidian-excalidraw-plugin#736]
I am wondering if this issue goes here or in the emoji toolbar repo https://github.com/oliveryh/obsidian-emoji-toolbar, if the last, i'll close it. Also im not sure if could be related to #734 in some way.

But when i try to use the emoji toolbar inside a sketch (Excalidraw 1.7.10), an exception "Cannot read properties of undefined  (reding 'getElementsByTagName')" comes up, then clicking the emoji button don't insert the desired emoji in the drawing (inside a text element).
![image](https://user-images.githubusercontent.com/31860235/183988511-458d2423-53c9-4120-9b8c-cb861bc9f4c9.png)

I have another vault with Excalidraw 1.7.11, there the exception doesn't appear, but the emoji is not inserted in the sketch neither.

Edit:  The emoji bar works without problem inside any markdown document, it seems the problem only happens within Excalidraw (apparently)

**Comment by zsviczian** [comment]
I am sorry, but I don't think that this can be made to work easily.

The editor for text elements in Excalidraw is not accessible outside Excalidraw and definitely different from the Obsidian Markdown editor.

Some solution options:
- I use the built-in Emoji toolbar in Windows (i.e. Operating system level) that works without issues. 
- You could open the drawing in markdown mode and add emojis in Markdown mode, that will work without problem. 
- An Excalidraw Script Engine program could be written to insert emojis, but that would require work from the emoji toolbar developer to open up the toolbar for accessing via the Excalidraw script.
- Since the active Excalidraw document is accessible via Excalidraw Automate, thus with some work a feature could be added to the Emoji Toolbar plugin to insert emojis, but even then it could insert emojis as new text elements or the last character of a selected text element, not mid-sentence.

**Comment by pikatwinky** [comment]
Oh, it was my mistake sorry, i thought the emoji bar you were using in your videos was the obsidian's plugin emoji bar.
Thank you so much @zsviczian for the workarounds, I agree the easier and straightforward solution is using the built-in Window's emoji bar (which i didn't know till now, sorry)
I use Windows + Android in my workflow and since they both have an excelent emoji collection, i think it's not worth to implement this issue so im gonna close it. 
Thanks again
