### ISSUE TITLE
Excalidraw view won't open 'Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document'

### ISSUE THREAD

**Issue by Gomilu** [zsviczian/obsidian-excalidraw-plugin#746]
**Describe the bug**
1) Can't open a file in the excalidraw view
2)Only seems to be with one file
3) Message I receive is : 'unexpected end of JSON input' (as seen in the attached picture)
![Screenshot from 2022-08-17 16-25-45](https://user-images.githubusercontent.com/111446934/185181947-3392ac88-faea-4ec9-a271-7cf13a27aa22.png)

**Expected behavior**
I would like to see the drawing or somehow recuperate it 

 

**Environment (please complete the following information):**
 - OS including version: Linux PopOS,
 - Plugin version: 1.7.13
 - Obsidian version: 0.15.9

**Additional context**
Just occurred today.
I restarted excalidraw/obsidian because the arrows (number 5 hotkey) didn't show the 'attach' zone on the objects (still doesn't) . Once restarted, I noticed it not wanting to re-open in the ExcaliDraw view anymore.

If I can somehow recuperate this file would be nice.

Also: first time on github. Not very tech-savvy. If I  can be of support, please let me know.
Thanks for all in advance.

**Comment by zsviczian** [comment]
I am really sorry to hear you ran into this problem. 

The file seems to be corrupted, this could be because for some reason saving got interrupted midway through saving. If you have Obsidian Sync you can roll back to the last working version of the file. If you don't have Obsidian sync, you can try to upload the corrupted file here (you will need to zip it otherwise GitHub will not accept an .md file), then I can take a look to see if I can do some magic... but I don't want to create false expectations, I will likely not be able to do magic... however it is worth a try at least.

In the future, before closing Obsidian it is best to press the save button in Excalidraw. Excalidraw does automatically save, but rarely, this sort of issue does happen, when save was not able to complete.

**Comment by YogiLu** [comment]
Hey, thanks for your quick, helpful and authentic reply.

Save was not able to complete: I see, that makes sense. I will be careful now. 

Magic: wow, okay. Don't worry too much though - it is an important file but not essential. If you can see if it is easy to, please go ahead. 

I will also back up manually every month now :)



[My Practice.excalidraw (copy).zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9373046/My.Practice.excalidraw.copy.zip)

**Comment by Gomilu** [comment]
Hey, Thank you for your helpful, quick and authentic reply.

Saving: I understand. I will be careful from now on. Thanks!

Magic: Oh, that would be super if you give it a little look. But don't invest too much effort in it - the file is important to me,but nothing I can't recuperate within a couple of hours and it has no rush

I will also backup more often now :)


[My Practice.excalidraw (copy).zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9373069/My.Practice.excalidraw.copy.zip)

**Comment by zsviczian** [comment]
Apologies for the delay in getting back to you. I have good news. I was able to recover a good portion - though not all of your drawing:

For the future I recommend two things:
- do regular backups of large files not only drawings but your Vault. Subscribing to Obsidian Sync is a good solution - though it is a bit expensive.
- you could break this drawing into couple of smaller drawings and combine them into a single view by embedding the individual excalidraw parts. That way the file will be smaller and also having parts in separate files lowers the chances of information loss.

[fixed file.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9383845/fixed.file.zip)

**Comment by Gomilu** [comment]
Heey :)) 

Fantastic! Makes me very happy.

I will adhere to your recommendations from now on. 

Dearest Thanks!
