### ISSUE TITLE
Excalidraw can't save the file in time up 1.7.9 

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#747]
**Describe the bug**
I use a script "Add Link to Existing File and Open" in version after 1.7.9 - 10,11,12,13 you have to manually save the file to save the link.

**To Reproduce**

https://user-images.githubusercontent.com/71871141/185201844-280dff63-4f87-4d3f-8b5d-b35684ce2a16.mp4

1. install a version higher than 1.7.9
2. paste the link to the selected object on the canvas
3. immediately (without interacting with the objects on the canvas) follow the link

**Expected behavior**
Saves drawing with pasted link as before in 1.7.9.

Thank you for your attention !🌻

**Comment by zsviczian** [comment]
This issue is a typical tip of the iceberg issue.

This seems to coincide with excalidraw.com moving to React 18. I've come across some similar issues in other parts of the code... something to do with a limitation of one update per animation frame... simply working from empirical experience. This is going to be a bigger headache but is an absolute priority to figure out since I have no idea what else might be impacted in the code.

**Comment by zsviczian** [comment]
resolved in 1.7.14. Hopefully, this will resolve a number of other hidden issues that stem from the React 18 upgrade.

**Comment by anatoliibakhtin** [comment]
@zsviczian thank you so much for your work ! I was damn lucky (you are interested, you answer quickly, although there are many other things to do and still add innovations🎉) to find you with this plugin in obsidian!
