### ISSUE TITLE
Support for tags per YAML front matter

### ISSUE THREAD

**Issue by neugartf** [zsviczian/obsidian-excalidraw-plugin#77]
**Is your feature request related to a problem? Please describe.**
I struggle to find drawings since they (to my knowledge) don't support tags.

**Describe the solution you'd like**
The *.md files could support tags based on the https://help.obsidian.md/Advanced+topics/YAML+front+matter

Keep up the good work!

**Comment by zsviczian** [comment]
I have been thinking about this... as of right now, excalidraw is not an *.md file, thus it does not have front matter, nor tags, nor backlinks. I am thinking to explore how the kanban plugin works, since it uses .md file, and will try to mimic that with Excalidraw. However, this requires quite an invasive change to the current setup, also I am not yet sure how it would work.

I will keep your request in mind.

**Comment by zsviczian** [comment]
I'll be releasing version 2.0 for testing this weekend. It will support tagging in frontmatter.

**Comment by zsviczian** [comment]
YAML front matter is supported in [1.2.0-alpha-1](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases)
