### ISSUE TITLE
Set our custom excalidraw app

### ISSUE THREAD

**Issue by seriaati** [zsviczian/obsidian-excalidraw-plugin#791]
**Is your feature request related to a problem? Please describe.**
I very much need the feature that allows me to change the color of part of a text, and searching this on google leads me to: https://github.com/excalidraw/excalidraw/issues/1126 then https://github.com/excalidraw/excalidraw/pull/5150.
I found that you can use this beta feature on https://excalidraw-git-fork-tom-sherman-text-color-ranges-excalidraw.vercel.app/

**Describe the solution you'd like**
I would like to be able to use https://excalidraw-git-fork-tom-sherman-text-color-ranges-excalidraw.vercel.app/ instead of the default excalidraw app with the plugin.

**Describe alternatives you've considered**
I can open https://excalidraw-git-fork-tom-sherman-text-color-ranges-excalidraw.vercel.app/ in my browser but I lose the format once I paste it into the plugin's excalidraw.

**Comment by zsviczian** [comment]
I wasn't aware of this fork. I could also possibly bring it over to the Obsidian fork... but I need to think about it... Each customization that is implemented takes Excalidraw a step further from the core excalidraw.com product and makes it ever harder to deploy excalidraw.com enhancements to Obsidian.

Having looked at the fork you mention I can already see challenges with how it would treat transcluded text and hyperlinks. The Obsidian plugin changes the text, thus the coloring logic would not work the same way.

In response to your question, simply using this other fork instead of the one built for the Obsidian plugin is not possible. I have my own fork with over 400 additional commits compared to the one on excalidraw.com. The plugin will simply not work with just another Excalidraw fork.

**Comment by seriaati** [comment]
okay, thank you for your response
