### ISSUE TITLE
Plans for Logseq

### ISSUE THREAD

**Issue by 4abhinavjain** [zsviczian/obsidian-excalidraw-plugin#821]
**Is your feature request related to a problem? Please describe.**
I love the plugin that you have made. Obsidian is a great tool as well but is not open-source. It is true that notes are all stored in markdown, but an open-source platform is always preferred.

**Describe the solution you'd like**
Logseq [https://github.com/logseq/logseq] is an open-source alternative to Obsidian which is very similar to Obsidian and is gaining traction. It will great to have this plugin for Logseq. 

Have you considered this?

**Comment by zsviczian** [comment]
True, the Obsidian engine is not open source, but your content is markdown and accessible regardless of the tool you use. When it comes to PKM I believe that frequently switching tools is a bad idea as it will inevitably result in knowledge loss. Obsidian meets all my needs currently. I don't plan to switch. Since the Obsidian-Excalidraw project is first and foremost a passion project, I don't see myself supporting multiple platforms. I don't see myself getting involved with LogSeq in the foreseeable future.

**Comment by zsviczian** [comment]
I've recently tested Whiteboard (based on TLDraw) for Logseq. It is looking very promising with many similar features to Excalidraw in Obsidian. As I understand the alpha release is coming soon.
