### ISSUE TITLE
after version 1.7.21 update

### ISSUE THREAD

**Issue by thremaana** [zsviczian/obsidian-excalidraw-plugin#824]
**all boxes inside the drawing board,automatically getting bigger.
![excali](https://user-images.githubusercontent.com/114383054/192206075-12ae8965-65f5-4aee-9c8d-e7a4f4ed4231.png)
**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS including version: [e.g. iOS 15.1, Android 9, Windows 11, etc]
 - Plugin version: 
 - Obsidian version: 

**Additional context**

**Comment by Leyeev** [comment]
Have the same problem after updating, I have tried to reinstall it. It is still the same

**Comment by zsviczian** [comment]
I've taken Excalidraw 1.7.21 off until I figure out what is going on.
In the new version I included new code from Excalidraw.com that effects sizing of boxes, so that could be the root cause, however I haven't experienced these issues myself.
Can you send me a sample file where this is happening so I can test and reproduce the issue?

**Comment by zsviczian** [comment]
I was able to reproduce the issue. I will investigate.

**Comment by thremaana** [comment]
OK THANK YOU
