### ISSUE TITLE
Make new md format optional

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#85]
Hi,

First off, thanks for all your work to integrate Excalidraw with Obsidian so smoothly.  It's made a huge difference to me.

I use both LogSeq and Obsidian on the same vault - at the moment they play nicely enough together that this allows me to use the advantages of both.  Both Obsidian and LogSeq can embed Excalidraw drawings in pages and any changes I make to a drawing in one tool are then reflected in the other.  I also embed some of my drawings into Jira - which also supports Excalidraw (I wish Confluence did as well but that's another story :-)).

If I upgrade to the latest version of your plugin that saves files as .md files I'm assuming this makes the drawings proprietary to Obsidian and they will no longer work in LogSeq or Jira.

If that is so, would it be possible to have a toggle in the settings that means drawings as still saved as .excalidraw files rather than .md files.  I understand that would mean foregoing some of the cool new features you have added, but for my use case inter-operability is a key feature I would be sad to lose.

If that's not possible, would it be okay to make a fork of the 1.1.8 release and stick with that - I'm afraid if I stick with the main branch I'm going to upgrade by mistake at some point.

Thanks,
David

**Comment by zsviczian** [comment]
This is a tough one.

I don't think having two Excalidraw versions in Community Plugins would be a good solution. 

[1.1.10](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.1.10) will continue to be available on GitHub, so even if you accidentally upgrade to 1.2.x, you can always downgrade to 1.1.10 albeit with some manual steps.

1.2 includes an export feature to save your drawing as *.excalidraw for portability. I could add a setting to automatically maintain an *.excalidraw replica of your drawing, similar to the .png and .svg options already available in 1.1.x. I could also add a feature to monitor if the native .excalidraw file's modified date is more recent than the Obsidian Excalidraw file's, in which case the files would be synched (overwriting the .md file with the changed drawing. This way you could enjoy the benefit of both worlds.

Does this make sense? Would this be an OK solution for you?

**Comment by zsviczian** [comment]
Please test [Excalidraw 1.2.0 Alpha 4](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.2.0-alpha-4)

I hope this provides sufficient compatibility:
![image](https://user-images.githubusercontent.com/14358394/124828115-23396b80-df77-11eb-9b49-7fdafcea12d8.png)

Please let me know! Thank you.

**Comment by dcoales** [comment]
That sounds like a great solution.  Thanks so much.  I'm going to be pushed for time today and tomorrow but I'll download and try it out over the weekend.

Thanks again.

**Comment by zsviczian** [comment]
I've played a little with Logseq / Obsidian / Excalidraw today. Unfortunately, the experience is not really smooth. 
1) During the conversion of the drawing the Logseq link breaks due to file name changes (I have "Automatically update internal links" enabled in Obsidian)
  - Clicking convert on a file will change the filename from drawing.excalidraw to drawing.excalidraw.md. This is good in Obsidian, as the old links pointing to the old drawing.excalidraw continue to work, as Obsidian will simply assume the .md file extension. Also this minimizes the risk of filename conflicts (if I would change the filename from drawing.excalidraw to drawing.md I would very likely have file name conflicts)
  - When I open the converted drawing and close it (with "Auto-export Excalidraw" option turned on), a new file is created with the name drawing.excalidraw.excalidraw (because the auto export simply replaces .md with .excalidraw). The Logseq link however needs to be updated manually.
  - With some editing of filenames you can clean up the links, but still [[draws/file.excalidraw]] will not open the drawing in Obsidian, to have the drawing also open in Obsidian (parallel to Logseq), you will need a second link on the page: with the format ![[draws/file.md]]

I don't yet have a good solution for you. :(

**Comment by zsviczian** [comment]
Please install [Excalidraw 1.2.0 Beta 1](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.2.0-beta-1). When you start it for the first time, do not convert files using the popup dialog. Convert files individually instead, by right-clicking on *.excalidraw files in the Obsidian File Explorer and selecting "*.excalidraw => *.md (Logseq compatibility)". Don't forget to also set "Compatibility Features" in settings to keep *.md files with *.excalidraw files in sync. This setup now works relatively well... though because of the difference in markdown dialect, I still find the coop between Logseq and Obsidian has too much friction... 

As a side comment, I find Logseq quite unpredictable when it comes to saving .excalidraw drawings. Even though I navigate away from a page, I found that the .excalidraw file in the draws/ folder is not always updated...

**Comment by zsviczian** [comment]
So I couldn't rest until this issue is properly resolved. I implemented backward compatibility. Now "legacy" *.excalidraw files work, albeit with the limitation that all the markdown-based goodies are unavailable.

With the sync features implemented in Beta 1, and the backward compatibility now implemented in [Excalidraw 1.2.0 Beta 2](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.2.0-beta-2) I believe I have an almost 100% solution to your issue. 

The only remaining backward compatibility I need to sort out is the hover pre-view on Exacalidraw links when using .excalidraw files. All else should work.

Please test and let me know if things are working ok.

**Comment by zsviczian** [comment]
[Excalidraw 1.2.0 Release Candidate 1](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.2.0-rc-1) now provides a full solution.

**Comment by zsviczian** [comment]
Published 1.2.0 to Community Plugins. It includes backward compatibility. Thanks for pointing the need for this out! I am much more comfortable with the update by being able to give people the flexibility to convert their files or not... depending on their personal preferences.

**Comment by dcoales** [comment]
Wow, what can I say.  That's fantastic.  I really appreciate the effort.
I've tried it out and everything seems to be working fine so far.

Thank you so much,
David Coales
