### ISSUE TITLE
BUG: `Default width of embedded (transcluded) image` is not working

### ISSUE THREAD

**Issue by kagerouttepaso** [zsviczian/obsidian-excalidraw-plugin#887]
**Describe the bug**
`Default width of embedded (transcluded) image` is not working.
If the beginning of the excalidraw.md file is a number, the value of max-width will be that number.
Example) 2022-11-16_edit.excalidraw.md -> max-width: 2022px

**To Reproduce**
1. Insert image in `![2022-11-16_edit.excalidraw.md](2022-11-16_edit..excalidraw.md)` format
1. Insert image in `![100.excalidraw.md](100.excalidraw.md)` format
1. Insert image in `![notnumber.excalidraw.md](notnumber.excalidraw.md)` format
1. Check the Styles of the inserted image in Developer Tools.

**Expected behavior**
All `Default width of embedded (transcluded) image` setting values become max-width values.

**Additional context**

#886 
In the case of this issue, it was set to 90%, but 2022px is set because the timestamp is at the beginning of the file name.

**Comment by zsviczian** [comment]
I can reproduce.
Root cause seems different for 1. and 2.
1 - seems to be within my plugin. I will fix this.
2 - seems to be an issue in Obsidian. Try creating just a blank markdown file called `100.md` and transcluding it. If you check the internal-embed div it will have width=100 as well. I'll raise this with the Obsidian devs.

**Comment by zsviczian** [comment]
https://forum.obsidian.md/t/full-number-alttext-recognized-as-image-width-is-that-normal/19578

Obsidian devs have acknowledged the issue. I hope a solution will be provided in the next Obsidian update. 🤞
