### ISSUE TITLE
BUG: Latex rendering

### ISSUE THREAD

**Issue by huncut2016** [zsviczian/obsidian-excalidraw-plugin#936]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.3
	Operating system: #1 SMP PREEMPT_DYNAMIC Fri Dec 2 20:47:45 UTC 2022 6.0.11-300.fc37.x86_64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Latex Suite v1.6.7
		2: TikZJax v0.5.1
		3: Advanced Tables v0.18.0
		4: Dataview v0.5.47
		5: Excalidraw v1.8.4

**Describe the bug**
Opening my note the image is not rendered correctly if I am using LaTex in excalidraw.

**To Reproduce**
First version to reproduce the behavior:
> 1. Open some vault **A** with an older release of excalidraw than the current
> 2. Open a **B** vault
> 3. Close **A**
> 4. Open a drawing with Latex init
> 5. See the error

Second version to reproduce the behavior:
> 1. Open some vault **A** with an older release of excalidraw than the current
> (Optional) 2. Update the plugin
> 3. Open a drawing with Latex init
> 4. See the error

Third version to reproduce the behavior:
Thanks to some fluctuating behavior:
1. Open a simple note on a bad day
2. See the error

**Expected behavior**
My drawing

**Screenshots**
## Rendered image in my note
![image](https://user-images.githubusercontent.com/56272960/206900354-0c4f6ad3-6593-4530-9a9d-636418c1434f.png)
## Drawing in the editor
![image](https://user-images.githubusercontent.com/56272960/206900379-9e8e3db8-a1f0-423d-9f5e-b7a3cd441a71.png)

**Additional context**
Previous versions have these problems but the occurrence was very small.
**How to solve the problem**
> After some reopening (as far as I'm concerned if the cache was deleted, the new fresh plugin would be loaded)  the problem disappears.

**Comment by zsviczian** [comment]
This is because for some reason the Mathjax library does not download to your device. This could be due to corporate firewalls, or many other reasons. Try setting a different mirror for downloading the mathjax library:

![image](https://user-images.githubusercontent.com/14358394/207953165-2c0e02a5-5214-4aac-aa9f-2028ffb2282a.png)

**Comment by huncut2016** [comment]
Ohh, thank you! 
But some questions were shown up in my mind.
Why does the plugin have to fetch MathJax? 
If I'm well-informed Obsidian uses a local (pre-downloaded) version of MathJax. It is not available through the API? If that's the case why you aren't embedding it into the plugin as a dependency? 
(If it's too long to write, I could check the code to save you a little time )

**Comment by zsviczian** [comment]
Unfortunately Obsidian only has the tex-chtml package loaded and I need the tex-svg package. This causes lots of other issues (for me), because mathjax is loaded to the Window object as a global variable... thus I need to load the tex-svg package to a hidden iframe for it to work parallel to the Obsidian pre-loaded package.

I aked liam to include the tex-svg package, but he did not seem open to the idea...

Now, I could include the tex-svg package in the main.js, but some people already complain that Excalidraw loads slow, this would increase the load time, so I decided that users who want latex will be ok with having this packge loaded from remote. (everything else in the Excalidraw package is 100% local)

**Comment by huncut2016** [comment]
You could lazy-load the package when the user clicks on the LaTex button.

**Comment by zsviczian** [comment]
addressed in 1.9.25
