### ISSUE TITLE
FR: Open embedded excalidraw as an image

### ISSUE THREAD

**Issue by jzhang-brex** [zsviczian/obsidian-excalidraw-plugin#939]
**Is your feature request related to a problem? Please describe.**

I embed an excalidraw in another page

```
![[Foo.excalidraw.md]]
```

When I click on it in the preview mode, it opens the Excalidraw canvas.

**Describe the solution you'd like**

I want to open an enlarged image by default and only enter Excalidraw with a certain modifier key (e.g. control)

**Describe alternatives you've considered**

**Additional context**

This is the behavior on mobile. I go through the setting of Excalidraw and can't figure out whether this is already supported.

**Comment by skyline-123** [comment]
That's right. When I use it on my mobile phone, I prefer to open the picture preview mode instead of entering the exclidraw editing mode.

In the preview mode of the mobile phone or tablet, occasionally the picture preview will be opened, but occasionally it will enter the editing mode of excalidraw, which troubles me.

**Comment by zsviczian** [comment]
makes sense. I implemented this in 1.8.5 

![image](https://user-images.githubusercontent.com/14358394/207947538-9fa73189-b50d-496a-9002-2ae06779e5ab.png)
