### ISSUE TITLE
BUG: Embedding selected element. Only part of grouped element is shown.

### ISSUE THREAD

**Issue by str-enjo** [zsviczian/obsidian-excalidraw-plugin#957]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.19043
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 80
	Plugins enabled: 44
		1: Dynamic Table of Contents v0.0.27
		2: Calendar v1.5.10
		3: Media Extended v2.11.1
		4: Editor Syntax Highlight v0.1.3
		5: Fullscreen mode plugin v0.1.2
		6: Banners v1.3.3
		7: Convert url to preview (iframe) v0.5.0
		8: Customizable Sidebar v2.2.1
		9: Obsidian Memos v1.9.7
		10: Search on Internet v0.5.0
		11: Paste URL into selection v1.7.0
		12: Day Planner v0.5.8
		13: Relative Line Numbers v2.0.1
		14: Typewriter Scroll v0.2.2
		15: Highlightr v1.2.2
		16: Focus Mode v1.11.4
		17: Dangerzone Writing v0.0.11
		18: Diagrams v1.5.0
		19: Dialogue v1.0.2
		20: Settings Search v1.2.0
		21: Advanced Tables v0.18.1
		22: Recent Files v1.3.5
		23: Vimrc Support v0.8.0
		24: Quick Switcher++ v2.3.5
		25: Hider v1.2.4
		26: Minimal Theme Settings v6.1.1
		27: Templater v1.16.0
		28: Emoji Toolbar v0.3.2
		29: Obsidian Charts v3.7.1
		30: Checklist v2.2.12
		31: Dataview v0.5.47
		32: Buttons v0.4.19
		33: Obsidian Tabs v1.0.7
		34: Excalidraw v1.8.7
		35: Tasks v1.21.0
		36: Collapse All v1.5.3
		37: QuickAdd v0.8.0
		38: Theme Picker v1.0.8
		39: Reminder v1.1.15
		40: Completr v3.1.0
		41: Full Calendar v0.9.5
		42: Hover Editor v0.11.8
		43: Obsidian Columns v1.4.0
		44: Omnisearch v1.9.1

**Describe the bug**
Trying to embed markdown link for selected element. In result get only part of image. When I group everything besides CPU square and try to embed it, I empty pane.

**To Reproduce**
1. Group elements and select
2. Click Shift+mouse1 on "Copy Markdown link for selected element"
3. Paste to markdown file

**Expected behavior**
Embed whole grouped element from excalidraw file.

**Screenshots**
Element that I expected to see:
![image](https://user-images.githubusercontent.com/97307533/210080029-23184d83-5dea-4df6-8c51-9c2d32545a04.png)

Result:
![image](https://user-images.githubusercontent.com/97307533/210080359-090e45d0-537f-4a12-8503-3b68eec718e6.png)

**Comment by zsviczian** [comment]
This is working as designed. Groups do not have element IDs in Excalidraw. So when you select the group and click on the get link icon, you get the link for the largest element in the group. When you use `[[link#^group=block_id]]` then the plugin checks the different groups the element belongs to and displays elements from the largest of those groups.

When you use the `[[link#^area=block_id]]` format, then the plugin takes the element you selected and crops the final drawing to show only that area of the image that has the element identified with the block id.

group reference is good if you don't want to see accidental overlapping lines from other groups in the cut-out. The area reference is a good choice if you want to see everything, including accidentally crossing lines from other objects.

In your case, I would actually recommend using the `group=` reference instead of the area.

If you still want the area for some reason, then add a rectangle around the area you want to show and make that rectangle transparent by setting `transparent` as both the stroke and background colors. Group the rectangle with the rest of the elements in your Multithreading theme, and copy the link that way.

Hope this helps.
