### ISSUE TITLE
BUG: Created drawing with image inverts image colour

### ISSUE THREAD

**Issue by badjerphoenix** [zsviczian/obsidian-excalidraw-plugin#979]
**Describe the bug**
When on the iPad Pro I have some images that are in my attachments. When I placed into the Excalidraw plug in the colours became inverted. These same drawings via the plug in on the PC look normal as you would expect

**To Reproduce**
Steps to reproduce the behavior

**Screenshots**

**Additional context**
Images were originally taken from the PC. Noticed this issue when I set up my new iPad. Only occurs on the iPad though & not the PC
![2023-01-16 18 33 59](https://user-images.githubusercontent.com/78933852/212786754-10415eef-2e17-4b27-9090-e0312a5c9228.png)

**Comment by zsviczian** [comment]
Unfortunately there is nothing I can do about this. This is one of the many things that Safari simply does not support. (on an iPad Obsidian runs on a Safari, and unfortunately Apple does not allow changing the web component on iPads... by the way, this is changing, at least in Europe, as there was a recent regulation that mandates Apple to open up this API as they ruled this is the same practice as Microsoft did with Internet Explorer back in the early 2000s 🎉).

Since implementing dynamic styling: https://youtu.be/LtR04fNTKTM I've personally stopped using dark mode. Dark mode was developed for online collaboration where one user uses Excalidraw in light mode, the other in dark. In Obsidian I am the only user working on the drawing, I rather set a dark background and use light colors (and have vibrant colors) than use dark mode.
For this you also may want to implement a custom color palette: https://youtu.be/epYNx2FSf2w
