### ISSUE TITLE
FR: Opacity support in pen settings

### ISSUE THREAD

**Issue by mikebarkmin** [zsviczian/obsidian-excalidraw-plugin#991]
The new feature of configuring a pen in a dedicated ui is really great, but I would like to see an opacity setting for a pen. 

The highlighter does work well, when highlighting text written in excalidraw. But it does not work well, when highlighting, for example, an image. 

For this scenario, I would like to define a pen with a certain opacity, so I can draw above the image.

Thanks for the great release :)

**Comment by zsviczian** [comment]
I did not think of that use case...
If you'd like and are comfortable with messing around with the data.json file, you can manually configure the opacity for the pen. 

Exit Obsidian.
Navigate to the `.obsidian/plugins/obsidian-excalidraw-plugin` folder.
Open the `data.json` file for editing (you might want to create a backup of the file just to be sure...)
Scroll almost to the end of the file, or search for the `"customPens": [` string.
You will see the pens listed here.
Look for the pen you want to edit and change the stroke color by adding two extra digits (this will set the opacity).
In the example in the picture, I am changing the stroke's opacity to 50% by adding `80` to the end. Writing `FF` instead of `80` would result in a fully opaque color and `00` in a fully transparent one.
Hope this helps.

![image](https://user-images.githubusercontent.com/14358394/215357043-c3df0f51-f534-4604-a1ae-69d02a43528d.png)

![image](https://user-images.githubusercontent.com/14358394/215357053-8e75d24d-0184-4085-8068-2299fdedd2f6.png)

**Comment by zsviczian** [comment]
I added support for this in 1.8.13. Will release today.
